// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_INPUTEDITOR_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the text. \
  * \
  * @param[in] text The text to display in UTF-8 format. \
  */ \
  ChildClass& SetText(const Dali::String& text) { InputEditor::SetText(text); return *this; } \
  /** \
  * @brief Sets the font family of the text. \
  * \
  * @param[in] fontFamily The requested font family to use. \
  */ \
  ChildClass& SetFontFamily(const Dali::String& fontFamily) { InputEditor::SetFontFamily(fontFamily); return *this; } \
  /** \
  * @brief Sets the font size of the text. \
  * \
  * @param[in] fontSize The font size in pixels. \
  */ \
  ChildClass& SetFontSize(float fontSize) { InputEditor::SetFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets the color of the text. \
  * \
  * @param[in] color The required text color value. \
  */ \
  ChildClass& SetTextColor(const UiColor& color) { InputEditor::SetTextColor(color); return *this; } \
  /** \
  * @brief Sets the line wrap mode. \
  * \
  * @param[in] mode The line wrap mode to apply. \
  */ \
  ChildClass& SetLineWrapMode(Text::LineWrapMode mode) { InputEditor::SetLineWrapMode(mode); return *this; } \
  /** \
  * @brief Sets the horizontal alignment of the text within the inputEditor. \
  * \
  * @param[in] alignment The horizontal text alignment. \
  */ \
  ChildClass& SetHorizontalTextAlignment(Text::Alignment alignment) { InputEditor::SetHorizontalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the vertical alignment of the text within the inputEditor. \
  * \
  * @param[in] alignment The vertical text alignment. \
  */ \
  ChildClass& SetVerticalTextAlignment(Text::Alignment alignment) { InputEditor::SetVerticalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the overflow mode. \
  * \
  * @param[in] mode The overflow mode to apply. \
  */ \
  ChildClass& SetOverflowMode(Text::OverflowMode mode) { InputEditor::SetOverflowMode(mode); return *this; } \
  /** \
  * @brief Sets the placeholder text displayed when the input editor is empty. \
  * \
  * @param[in] text The placeholder text in UTF-8 encoding. \
  */ \
  ChildClass& SetPlaceholder(const Dali::String& text) { InputEditor::SetPlaceholder(text); return *this; } \
  /** \
  * @brief Sets the color of the placeholder text. \
  * \
  * @param[in] color The placeholder text color as a UiColor. \
  */ \
  ChildClass& SetPlaceholderColor(const UiColor& color) { InputEditor::SetPlaceholderColor(color); return *this; } \
  /** \
  * @brief Sets whether the placeholder text is shown when the input editor has focus. \
  * \
  * @param[in] enabled True to show the placeholder text when focused, false otherwise. \
  */ \
  ChildClass& SetShowPlaceholderOnFocus(bool enabled) { InputEditor::SetShowPlaceholderOnFocus(enabled); return *this; } \
  /** \
  * @brief Sets the width of the text cursor. \
  * \
  * @param[in] width The cursor width in pixels. \
  */ \
  ChildClass& SetCursorWidth(int width) { InputEditor::SetCursorWidth(width); return *this; } \
  /** \
  * @brief Sets the color of the text cursor \
  * \
  * This color is applied to both primary and secondary cursors \
  * when a split cursor is shown in bidirectional text. \
  * \
  * @param[in] color The cursor color as a UiColor. \
  */ \
  ChildClass& SetCursorColor(const UiColor& color) { InputEditor::SetCursorColor(color); return *this; } \
  /** \
  * @brief Sets whether the cursor should blink. \
  * \
  * @param[in] enabled True to enable cursor blinking, false otherwise. \
  */ \
  ChildClass& SetCursorBlinkEnabled(bool enabled) { InputEditor::SetCursorBlinkEnabled(enabled); return *this; } \
  /** \
  * @brief Sets the time interval in seconds between cursor on and off states. \
  * \
  * @param[in] interval The cursor blink interval in seconds. \
  */ \
  ChildClass& SetCursorBlinkInterval(float interval) { InputEditor::SetCursorBlinkInterval(interval); return *this; } \
  /** \
  * @brief Sets the cursor position. \
  * \
  * The position is specified as a character index in the current text. \
  * \
  * @param[in] position The cursor position. \
  */ \
  ChildClass& SetCursorPosition(uint32_t position) { InputEditor::SetCursorPosition(position); return *this; } \
  /** \
  * @brief Sets whether text selection is enabled. \
  * \
  * @param[in] enabled True to enable text selection, false otherwise. \
  */ \
  ChildClass& SetSelectionEnabled(bool enabled) { InputEditor::SetSelectionEnabled(enabled); return *this; } \
  /** \
  * @brief Sets the highlight color of the selected text region. \
  * \
  * @param[in] color The selection highlight color as a UiColor. \
  */ \
  ChildClass& SetSelectionColor(const UiColor& color) { InputEditor::SetSelectionColor(color); return *this; } \
  /** \
  * @brief Sets whether text editing handles are enabled. \
  * \
  * Text editing handles include the cursor handle (shown below the insertion cursor) \
  * and the left/right selection handles (shown at both ends of the selected text range). \
  * \
  * @param[in] enabled True to enable text editing handles, false otherwise. \
  */ \
  ChildClass& SetTextHandleEnabled(bool enabled) { InputEditor::SetTextHandleEnabled(enabled); return *this; } \
  /** \
  * @brief Sets the color of the text editing handles. \
  * \
  * This color is applied to both the cursor handle and the left/right selection handles. \
  * \
  * @param[in] color The text editing handle color as a UiColor. \
  */ \
  ChildClass& SetTextHandleColor(const UiColor& color) { InputEditor::SetTextHandleColor(color); return *this; } \
  /** \
  * @brief Sets the cursor handle image. \
  * \
  * The cursor handle is shown below the insertion cursor when there is no selection range. \
  * \
  * @param[in] image The cursor handle image URL. \
  */ \
  ChildClass& SetCursorHandleImage(const Dali::String& image) { InputEditor::SetCursorHandleImage(image); return *this; } \
  /** \
  * @brief Sets the pressed cursor handle image. \
  * \
  * The cursor handle is shown below the insertion cursor when there is no selection range. \
  * \
  * @param[in] image The pressed cursor handle image URL. \
  */ \
  ChildClass& SetCursorHandlePressedImage(const Dali::String& image) { InputEditor::SetCursorHandlePressedImage(image); return *this; } \
  /** \
  * @brief Sets the left selection handle image. \
  * \
  * The selection handle is shown at the left bound of the selected text range. \
  * \
  * @param[in] image The left selection handle image URL. \
  */ \
  ChildClass& SetSelectionHandleImageLeft(const Dali::String& image) { InputEditor::SetSelectionHandleImageLeft(image); return *this; } \
  /** \
  * @brief Sets the right selection handle image. \
  * \
  * The selection handle is shown at the right bound of the selected text range. \
  * \
  * @param[in] image The right selection handle image URL. \
  */ \
  ChildClass& SetSelectionHandleImageRight(const Dali::String& image) { InputEditor::SetSelectionHandleImageRight(image); return *this; } \
  /** \
  * @brief Sets the pressed left selection handle image. \
  * \
  * The selection handle is shown at the left bound of the selected text range. \
  * \
  * @param[in] image The pressed left selection handle image URL. \
  */ \
  ChildClass& SetSelectionHandlePressedImageLeft(const Dali::String& image) { InputEditor::SetSelectionHandlePressedImageLeft(image); return *this; } \
  /** \
  * @brief Sets the pressed right selection handle image. \
  * \
  * The selection handle is shown at the right bound of the selected text range. \
  * \
  * @param[in] image The pressed right selection handle image URL. \
  */ \
  ChildClass& SetSelectionHandlePressedImageRight(const Dali::String& image) { InputEditor::SetSelectionHandlePressedImageRight(image); return *this; } \
  /** \
  * @brief Sets the maximum number of characters that can be entered into the InputEditor. \
  * \
  * @param[in] length The maximum number of characters allowed. \
  */ \
  ChildClass& SetMaximumLength(int length) { InputEditor::SetMaximumLength(length); return *this; } \
  /** \
  * @brief Sets the input filter. \
  * \
  * The input filter defines allow and deny patterns used to filter text \
  * before it is inserted. \
  * \
  * If an allow pattern is set, input that does not match the pattern is rejected. \
  * If a deny pattern is set, input that matches the pattern is rejected. \
  * \
  * If both patterns are set, input must match the allow pattern and must not \
  * match the deny pattern. \
  * \
  * @note This filter is applied to inserted input, such as user input, input \
  * method commits, and paste operations. It is not applied when text is set \
  * directly with SetText(). \
  * \
  * @param[in] inputFilter The input filter to apply. \
  * @return This input editor. \
  */ \
  ChildClass& SetInputFilter(const Text::InputFilter& inputFilter) { InputEditor::SetInputFilter(inputFilter); return *this; } \
  /** \
  * @brief Sets whether the InputEditor can be edited by user interaction. \
  * \
  * @param[in] editable True to allow editing, false otherwise. \
  */ \
  ChildClass& SetEditable(bool editable) { InputEditor::SetEditable(editable); return *this; } \
  /** \
  * @brief Sets how the layout direction of the text is resolved. \
  * \
  * - LayoutDirectionMode::CONTENTS: \
  *   The layout direction is determined from the text content itself. \
  * \
  * - LayoutDirectionMode::INHERIT: \
  *   The layout direction is inherited from the parent view. \
  * \
  * - LayoutDirectionMode::LOCALE: \
  *   The layout direction is determined based on the system locale. \
  * \
  * @note The default layout direction mode of InputEditor is LayoutDirectionMode::INHERIT. \
  * \
  * @param[in] mode The LayoutDirectionMode used to determine the text layout direction. \
  */ \
  ChildClass& SetLayoutDirectionMode(Text::LayoutDirectionMode mode) { InputEditor::SetLayoutDirectionMode(mode); return *this; } \
  /** \
  * @brief Enables or disables mark-up processing for the input text. \
  * \
  * When enabled, markup tags in the input text are interpreted and rendered \
  * accordingly. When disabled, the input text is treated as plain text. \
  * \
  * @param[in] enabled True to enable mark-up parsing, false to render text as plain string. \
  */ \
  ChildClass& SetMarkupEnabled(bool enabled) { InputEditor::SetMarkupEnabled(enabled); return *this; } \
  /** \
  * @brief Sets the font weight. \
  * \
  * @param[in] weight The font weight. \
  */ \
  ChildClass& SetFontWeight(Text::FontWeight weight) { InputEditor::SetFontWeight(weight); return *this; } \
  /** \
  * @brief Sets the font width. \
  * \
  * @param[in] width The font width. \
  */ \
  ChildClass& SetFontWidth(Text::FontWidth width) { InputEditor::SetFontWidth(width); return *this; } \
  /** \
  * @brief Sets the font slant. \
  * \
  * @param[in] slant The font slant. \
  */ \
  ChildClass& SetFontSlant(Text::FontSlant slant) { InputEditor::SetFontSlant(slant); return *this; } \
  /** \
  * @brief Sets the background color behind the text. \
  * \
  * The background is rendered behind the glyphs of the text. \
  * \
  * @param[in] color The text background color. \
  * \
  * @return This input editor. \
  */ \
  ChildClass& SetTextBackgroundColor(const UiColor& color) { InputEditor::SetTextBackgroundColor(color); return *this; } \
  /** \
  * @brief Sets the underline style. \
  * \
  * @param[in] underline The underline configuration. \
  */ \
  ChildClass& SetUnderline(const Text::Underline& underline) { InputEditor::SetUnderline(underline); return *this; } \
  /** \
  * @brief Sets the shadow style. \
  * \
  * @param[in] shadow The shadow configuration. \
  */ \
  ChildClass& SetShadow(const Text::Shadow& shadow) { InputEditor::SetShadow(shadow); return *this; } \
  /** \
  * @brief Sets the outline style. \
  * \
  * @param[in] outline The outline configuration. \
  */ \
  ChildClass& SetOutline(const Text::Outline& outline) { InputEditor::SetOutline(outline); return *this; } \
  /** \
  * @brief Sets the line-through style. \
  * \
  * @param[in] lineThrough The line-through configuration. \
  */ \
  ChildClass& SetLineThrough(const Text::LineThrough& lineThrough) { InputEditor::SetLineThrough(lineThrough); return *this; } \
  /** \
  * @brief Sets the font size scale. \
  * \
  * The scaled font size is calculated from the current font size \
  * multiplied by this scale value. \
  * \
  * @param[in] scale The font size scale. \
  */ \
  ChildClass& SetFontSizeScale(float scale) { InputEditor::SetFontSizeScale(scale); return *this; } \
  /** \
  * @brief Sets the minimum font size scale. \
  * \
  * If this value is greater than the maximum font size scale, \
  * the adjusted font size scale follows this minimum value. \
  * \
  * @param[in] scale The minimum font size scale. \
  */ \
  ChildClass& SetMinimumFontSizeScale(float scale) { InputEditor::SetMinimumFontSizeScale(scale); return *this; } \
  /** \
  * @brief Sets the maximum font size scale. \
  * \
  * If this value is less than the minimum font size scale, \
  * the adjusted font size scale follows the minimum font size scale. \
  * \
  * @param[in] scale The maximum font size scale. \
  */ \
  ChildClass& SetMaximumFontSizeScale(float scale) { InputEditor::SetMaximumFontSizeScale(scale); return *this; } \
  /** \
  * @brief Sets whether the system font size scale is applied. \
  * \
  * When enabled, the system font size scale is used instead of \
  * the user-defined font size scale before applying the minimum \
  * and maximum constraints. \
  * \
  * @param[in] enabled True to apply the system font size scale, false otherwise. \
  */ \
  ChildClass& SetSystemFontSizeScaleEnabled(bool enabled) { InputEditor::SetSystemFontSizeScaleEnabled(enabled); return *this; } \
  /** \
  * @brief Sets the text color used for typing. \
  * \
  * If a text range is selected, the color is applied to the selected text. \
  * If the selection is collapsed, the color is applied to text inserted after \
  * the current cursor position. \
  * \
  * @param[in] color The typing text color. \
  * @return This input editor. \
  */ \
  ChildClass& SetTypingTextColor(const UiColor& color) { InputEditor::SetTypingTextColor(color); return *this; } \
  /** \
  * @brief Sets the font family used for typing. \
  * \
  * If a text range is selected, the font family is applied to the selected text. \
  * If the selection is collapsed, the font family is applied to text inserted after \
  * the current cursor position. \
  * \
  * @param[in] fontFamily The typing font family. \
  * @return This input editor. \
  */ \
  ChildClass& SetTypingFontFamily(const Dali::String& fontFamily) { InputEditor::SetTypingFontFamily(fontFamily); return *this; } \
  /** \
  * @brief Sets the font size in pixels used for typing. \
  * \
  * If a text range is selected, the font size is applied to the selected text. \
  * If the selection is collapsed, the font size is applied to text inserted after \
  * the current cursor position. \
  * \
  * @param[in] fontSize The typing font size in pixels. \
  * @return This input editor. \
  */ \
  ChildClass& SetTypingFontSize(float fontSize) { InputEditor::SetTypingFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets the font weight used for typing. \
  * \
  * If a text range is selected, the font weight is applied to the selected text. \
  * If the selection is collapsed, the font weight is applied to text inserted after \
  * the current cursor position. \
  * \
  * @param[in] weight The typing font weight. \
  * @return This input editor. \
  */ \
  ChildClass& SetTypingFontWeight(Text::FontWeight weight) { InputEditor::SetTypingFontWeight(weight); return *this; } \
  /** \
  * @brief Sets the font width used for typing. \
  * \
  * If a text range is selected, the font width is applied to the selected text. \
  * If the selection is collapsed, the font width is applied to text inserted after \
  * the current cursor position. \
  * \
  * @param[in] width The typing font width. \
  * @return This input editor. \
  */ \
  ChildClass& SetTypingFontWidth(Text::FontWidth width) { InputEditor::SetTypingFontWidth(width); return *this; } \
  /** \
  * @brief Sets the font slant used for typing. \
  * \
  * If a text range is selected, the font slant is applied to the selected text. \
  * If the selection is collapsed, the font slant is applied to text inserted after \
  * the current cursor position. \
  * \
  * @param[in] slant The typing font slant. \
  * @return This input editor. \
  */ \
  ChildClass& SetTypingFontSlant(Text::FontSlant slant) { InputEditor::SetTypingFontSlant(slant); return *this; } \
  /** \
  * @brief Sets the font variation axes. \
  * \
  * This replaces all previously set font variation axes. \
  * \
  * If duplicate axis tags are provided, the last value is used. \
  * \
  * Unsupported axis tags may be ignored depending on the selected font. \
  * \
  * @param[in] axes The font variation axes. \
  */ \
  ChildClass& SetFontVariation(const Dali::Vector<Text::FontVariationAxis>& axes) { InputEditor::SetFontVariation(axes); return *this; } \
  /** \
  * @brief Sets the font variation from a settings string. \
  * \
  * The settings string consists of one or more pairs of axis tags and \
  * numeric values separated by commas. \
  * \
  * Supported formats include: \
  * - wght=700,wdth=90 (recommended) \
  * - "wght" 700, "wdth" 90 \
  * - 'wght' 700, 'wdth' 90 \
  * \
  * In quoted formats, the axis tag must be wrapped with single quotes \
  * (U+0027) or double quotes (U+0022). \
  * \
  * Each axis tag must contain exactly four printable ASCII characters \
  * in the range U+0020..U+007E. Space is allowed only as trailing \
  * characters in the axis tag. \
  * \
  * If duplicate axis tags are specified, the last value is used. \
  * \
  * If the input string is invalid, the font variation is not changed. \
  * \
  * Unsupported axis tags may be ignored depending on the selected font. \
  * \
  * @param[in] settings The font variation settings string. \
  */ \
  ChildClass& SetFontVariation(const Dali::String& settings) { InputEditor::SetFontVariation(settings); return *this; }
