// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_INPUTFIELD_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the text. \
  * \
  * @param[in] text The text to display in UTF-8 format. \
  */ \
  ChildClass& SetText(const Dali::String& text) { InputField::SetText(text); return *this; } \
  /** \
  * @brief Sets the font family of the text. \
  * \
  * @param[in] fontFamily The requested font family to use. \
  */ \
  ChildClass& SetFontFamily(const Dali::String& fontFamily) { InputField::SetFontFamily(fontFamily); return *this; } \
  /** \
  * @brief Sets the font size of the text. \
  * \
  * @param[in] fontSize The font size in pixels. \
  */ \
  ChildClass& SetFontSize(float fontSize) { InputField::SetFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets the color of the text. \
  * \
  * @param[in] color The required text color value. \
  */ \
  ChildClass& SetTextColor(const Vector4& color) { InputField::SetTextColor(color); return *this; } \
  /** \
  * @brief Sets the horizontal alignment of the text within the inputField. \
  * \
  * @param[in] alignment The horizontal text alignment. \
  */ \
  ChildClass& SetHorizontalTextAlignment(Text::Alignment alignment) { InputField::SetHorizontalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the vertical alignment of the text within the inputField. \
  * \
  * @param[in] alignment The vertical text alignment. \
  */ \
  ChildClass& SetVerticalTextAlignment(Text::Alignment alignment) { InputField::SetVerticalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the placeholder text displayed when the input field is empty. \
  * \
  * @param[in] text The placeholder text in UTF-8 encoding. \
  */ \
  ChildClass& SetPlaceholder(const Dali::String& text) { InputField::SetPlaceholder(text); return *this; } \
  /** \
  * @brief Sets the color of the placeholder text. \
  * \
  * @param[in] color The placeholder text color as a Vector4. \
  * \
  * @return A reference to this InputField for method chaining. \
  */ \
  ChildClass& SetPlaceholderColor(const Vector4& color) { InputField::SetPlaceholderColor(color); return *this; } \
  /** \
  * @brief Sets the width of the text cursor. \
  * \
  * @param[in] width The cursor width in pixels. \
  * \
  * @return A reference to this InputField for method chaining. \
  */ \
  ChildClass& SetCursorWidth(int width) { InputField::SetCursorWidth(width); return *this; } \
  /** \
  * @brief Sets the color of the text cursor \
  * \
  * This color is applied to both primary and secondary cursors \
  * when a split cursor is shown in bidirectional text. \
  * \
  * @param[in] color The cursor color as a Vector4. \
  * \
  * @return A reference to this InputField for method chaining. \
  */ \
  ChildClass& SetCursorColor(const Vector4& color) { InputField::SetCursorColor(color); return *this; } \
  /** \
  * @brief Sets the highlight color of the selected text region. \
  * \
  * @param[in] color The selection highlight color as a Vector4). \
  * \
  * @return A reference to this InputField for method chaining. \
  */ \
  ChildClass& SetSelectionColor(const Vector4& color) { InputField::SetSelectionColor(color); return *this; } \
  /** \
  * @brief Sets the maximum number of characters that can be entered into the InputField. \
  * \
  * @param[in] length The maximum number of characters allowed. \
  */ \
  ChildClass& SetMaximumLength(int length) { InputField::SetMaximumLength(length); return *this; }
