// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_LABEL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the text. \
  * \
  * @param[in] text The text to display in UTF-8 format. \
  */ \
  ChildClass& SetText(const Dali::String& text) { Label::SetText(text); return *this; } \
  /** \
  * @brief Sets the font family of the text. \
  * \
  * @param[in] fontFamily The requested font family to use. \
  */ \
  ChildClass& SetFontFamily(const Dali::String& fontFamily) { Label::SetFontFamily(fontFamily); return *this; } \
  /** \
  * @brief Sets the font size of the text. \
  * \
  * @param[in] fontSize The font size in pixels. \
  */ \
  ChildClass& SetFontSize(float fontSize) { Label::SetFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets whether the text should be multi-line. \
  * \
  * @param[in] multiLine True for multi-line layout, false for single-line layout. \
  */ \
  ChildClass& SetMultiLine(bool multiLine) { Label::SetMultiLine(multiLine); return *this; } \
  /** \
  * @brief Sets the color of the text. \
  * \
  * @param[in] color The required text color value. \
  */ \
  ChildClass& SetTextColor(const Vector4& color) { Label::SetTextColor(color); return *this; } \
  /** \
  * @brief Sets the horizontal alignment of the text within the label. \
  * \
  * @param[in] alignment The horizontal text alignment. \
  */ \
  ChildClass& SetHorizontalTextAlignment(Text::Alignment alignment) { Label::SetHorizontalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the vertical alignment of the text within the label. \
  * \
  * @param[in] alignment The vertical text alignment. \
  */ \
  ChildClass& SetVerticalTextAlignment(Text::Alignment alignment) { Label::SetVerticalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the line height of the text. \
  * \
  * The interpretation of this value depends on the current LineHeightMode. \
  * \
  * - If the mode is LineHeightMode::RELATIVE, the line height is calculated \
  *   as a multiplier of the font pixel size: \
  *   @code \
  *   CalculatedLineHeight(px) = FontSize(px) * lineHeight \
  *   @endcode \
  * \
  * - If the mode is LineHeightMode::ABSOLUTE, the value is treated as \
  *   an absolute line height in pixels. \
  * \
  * Setting lineHeight to -1.0f ensures enough vertical space to display \
  * the full font metrics (NaturalSize). This behavior is similar to the \
  * "Auto" line height option in design tools such as Figma. \
  * \
  * @note The final line height is clamped to be no smaller than \
  *       the natural line height derived from the font metrics. \
  * \
  * @param[in] lineHeight The line height value. \
  */ \
  ChildClass& SetLineHeight(float lineHeight) { Label::SetLineHeight(lineHeight); return *this; } \
  /** \
  * @brief Sets how the line height value is interpreted. \
  * \
  * - LineHeightMode::RELATIVE: \
  *   The line height is calculated as a multiplier of the font size. \
  * \
  * - LineHeightMode::ABSOLUTE: \
  *   The line height is treated as an absolute pixel value. \
  * \
  * The default mode is LineHeightMode::RELATIVE. \
  * \
  * @param[in] mode The line height mode. \
  */ \
  ChildClass& SetLineHeightMode(Text::LineHeightMode mode) { Label::SetLineHeightMode(mode); return *this; } \
  /** \
  * @brief Sets how the layout direction of the text is resolved. \
  * \
  * - LayoutDirectionMode::CONTENTS: \
  *   The layout direction is determined from the text content itself. \
  * \
  * - LayoutDirectionMode::INHERIT: \
  *   The layout direction is inherited from the parent view. \
  * \
  * - LayoutDirectionMode::LOCALE: \
  *   The layout direction is determined based on the system locale. \
  * \
  * @param[in] mode The LayoutDirectionMode used to determine the text layout direction. \
  */ \
  ChildClass& SetLayoutDirectionMode(Text::LayoutDirectionMode mode) { Label::SetLayoutDirectionMode(mode); return *this; }
