// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_LABEL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the text. \
  * \
  * @param[in] text The text to display in UTF-8 format. \
  */ \
  ChildClass& SetText(const Dali::String& text) { Label::SetText(text); return *this; } \
  /** \
  * @brief Sets the font family of the text. \
  * \
  * @param[in] fontFamily The requested font family to use. \
  */ \
  ChildClass& SetFontFamily(const Dali::String& fontFamily) { Label::SetFontFamily(fontFamily); return *this; } \
  /** \
  * @brief Sets the font size of the text. \
  * \
  * @param[in] fontSize The font size in pixels. \
  */ \
  ChildClass& SetFontSize(float fontSize) { Label::SetFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets whether the text should be multi-line. \
  * \
  * @param[in] multiLine True for multi-line layout, false for single-line layout. \
  */ \
  ChildClass& SetMultiLine(bool multiLine) { Label::SetMultiLine(multiLine); return *this; } \
  /** \
  * @brief Sets the line wrap mode. \
  * \
  * @param[in] mode The line wrap mode to apply. \
  */ \
  ChildClass& SetLineWrapMode(Text::LineWrapMode mode) { Label::SetLineWrapMode(mode); return *this; } \
  /** \
  * @brief Sets the color of the text. \
  * \
  * @param[in] color The required text color value. \
  */ \
  ChildClass& SetTextColor(const UiColor& color) { Label::SetTextColor(color); return *this; } \
  /** \
  * @brief Sets the horizontal alignment of the text within the label. \
  * \
  * @param[in] alignment The horizontal text alignment. \
  */ \
  ChildClass& SetHorizontalTextAlignment(Text::Alignment alignment) { Label::SetHorizontalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the vertical alignment of the text within the label. \
  * \
  * @param[in] alignment The vertical text alignment. \
  */ \
  ChildClass& SetVerticalTextAlignment(Text::Alignment alignment) { Label::SetVerticalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the line height of the text. \
  * \
  * The interpretation of this value depends on the current LineHeightMode. \
  * \
  * - If the mode is LineHeightMode::RELATIVE, the line height is calculated \
  *   as a multiplier of the font pixel size: \
  *   @code \
  *   CalculatedLineHeight(px) = FontSize(px) * lineHeight \
  *   @endcode \
  * \
  * - If the mode is LineHeightMode::ABSOLUTE, the value is treated as \
  *   an absolute line height in pixels. \
  * \
  * Setting lineHeight to -1.0f ensures enough vertical space to display \
  * the full font metrics (NaturalSize). This behavior is similar to the \
  * "Auto" line height option in design tools such as Figma. \
  * \
  * @note The final line height is clamped to be no smaller than \
  *       the natural line height derived from the font metrics. \
  * \
  * @param[in] lineHeight The line height value. \
  */ \
  ChildClass& SetLineHeight(float lineHeight) { Label::SetLineHeight(lineHeight); return *this; } \
  /** \
  * @brief Sets how the line height value is interpreted. \
  * \
  * - LineHeightMode::RELATIVE: \
  *   The line height is calculated as a multiplier of the font size. \
  * \
  * - LineHeightMode::ABSOLUTE: \
  *   The line height is treated as an absolute pixel value. \
  * \
  * The default mode is LineHeightMode::RELATIVE. \
  * \
  * @param[in] mode The line height mode. \
  */ \
  ChildClass& SetLineHeightMode(Text::LineHeightMode mode) { Label::SetLineHeightMode(mode); return *this; } \
  /** \
  * @brief Sets how the layout direction of the text is resolved. \
  * \
  * - LayoutDirectionMode::CONTENTS: \
  *   The layout direction is determined from the text content itself. \
  * \
  * - LayoutDirectionMode::INHERIT: \
  *   The layout direction is inherited from the parent view. \
  * \
  * - LayoutDirectionMode::LOCALE: \
  *   The layout direction is determined based on the system locale. \
  * \
  * @param[in] mode The LayoutDirectionMode used to determine the text layout direction. \
  */ \
  ChildClass& SetLayoutDirectionMode(Text::LayoutDirectionMode mode) { Label::SetLayoutDirectionMode(mode); return *this; } \
  /** \
  * @brief Enables or disables mark-up processing for the text. \
  * \
  * @param[in] enabled True to enable mark-up parsing, false to render text as plain string. \
  */ \
  ChildClass& SetMarkupEnabled(bool enabled) { Label::SetMarkupEnabled(enabled); return *this; } \
  /** \
  * @brief Sets the color of anchors in the text. \
  * \
  * @param[in] color The color to apply to anchors. \
  */ \
  ChildClass& SetAnchorColor(const UiColor& color) { Label::SetAnchorColor(color); return *this; } \
  /** \
  * @brief Sets the color of anchors when they are clicked. \
  * \
  * @param[in] color The color to apply to clicked anchors. \
  */ \
  ChildClass& SetAnchorClickedColor(const UiColor& color) { Label::SetAnchorClickedColor(color); return *this; } \
  /** \
  * @brief Sets the marquee speed. \
  * \
  * @param[in] speed The marquee speed in pixels per second. \
  */ \
  ChildClass& SetMarqueeSpeed(int speed) { Label::SetMarqueeSpeed(speed); return *this; } \
  /** \
  * @brief Sets the number of complete loops for marquee. \
  * \
  * @param[in] loopCount The number of loops. \
  */ \
  ChildClass& SetMarqueeLoopCount(int loopCount) { Label::SetMarqueeLoopCount(loopCount); return *this; } \
  /** \
  * @brief Sets the amount of time to delay the start of marquee and further loops. \
  * \
  * @param[in] delay The delay time in seconds. \
  */ \
  ChildClass& SetMarqueeLoopDelay(float delay) { Label::SetMarqueeLoopDelay(delay); return *this; } \
  /** \
  * @brief Sets the gap before marquee wraps. \
  * \
  * @param[in] gap The gap in pixels. \
  */ \
  ChildClass& SetMarqueeGap(int gap) { Label::SetMarqueeGap(gap); return *this; } \
  /** \
  * @brief Sets how the marquee stops. \
  * \
  * @param[in] stopMode The marquee stop mode. \
  */ \
  ChildClass& SetMarqueeStopMode(Text::MarqueeStopMode stopMode) { Label::SetMarqueeStopMode(stopMode); return *this; } \
  /** \
  * @brief Sets the marquee orientation. \
  * \
  * @param[in] orientation The marquee orientation. \
  */ \
  ChildClass& SetMarqueeOrientation(Text::MarqueeOrientation orientation) { Label::SetMarqueeOrientation(orientation); return *this; } \
  /** \
  * @brief Sets the font weight. \
  * \
  * @param[in] weight The font weight. \
  */ \
  ChildClass& SetFontWeight(Text::FontWeight weight) { Label::SetFontWeight(weight); return *this; } \
  /** \
  * @brief Sets the font width. \
  * \
  * @param[in] width The font width. \
  */ \
  ChildClass& SetFontWidth(Text::FontWidth width) { Label::SetFontWidth(width); return *this; } \
  /** \
  * @brief Sets the font slant. \
  * \
  * @param[in] slant The font slant. \
  */ \
  ChildClass& SetFontSlant(Text::FontSlant slant) { Label::SetFontSlant(slant); return *this; } \
  /** \
  * @brief Sets the underline style. \
  * \
  * @param[in] underline The underline configuration. \
  */ \
  ChildClass& SetUnderline(const Text::Underline& underline) { Label::SetUnderline(underline); return *this; }
