// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the width of the View. \
  * \
  * @param[in] width The width to set \
  */ \
  ChildClass& SetSizeWidth(float width) { View::SetSizeWidth(width); return *this; } \
  /** \
  * @brief Sets the height of the View. \
  * \
  * @param[in] height The height to set \
  */ \
  ChildClass& SetSizeHeight(float height) { View::SetSizeHeight(height); return *this; } \
  /** \
  * @brief Sets the X position of the View. \
  * \
  * @param[in] x The X position to set \
  */ \
  ChildClass& SetPositionX(float x) { View::SetPositionX(x); return *this; } \
  /** \
  * @brief Sets the Y position of the View. \
  * \
  * @param[in] y The Y position to set \
  */ \
  ChildClass& SetPositionY(float y) { View::SetPositionY(y); return *this; } \
  /** \
  * @brief Sets the parent origin of the View. \
  * \
  * @param[in] point The parent origin to set \
  */ \
  ChildClass& SetParentOrigin(const Vector3& point) { View::SetParentOrigin(point); return *this; } \
  /** \
  * @brief Sets the pivot point of the View. \
  * \
  * @param[in] point The pivot point to set \
  */ \
  ChildClass& SetPivotPoint(const Vector3& point) { View::SetPivotPoint(point); return *this; } \
  /** \
  * @brief Sets the layout width. \
  * \
  * Use LayoutDimension::WrapContent for content-based sizing, \
  * LayoutDimension::MatchParent to fill parent, or a positive value for fixed size. \
  * \
  * @param[in] width The layout width \
  */ \
  ChildClass& SetLayoutWidth(float width) { View::SetLayoutWidth(width); return *this; } \
  /** \
  * @brief Sets the layout height. \
  * \
  * @param[in] height The layout height \
  */ \
  ChildClass& SetLayoutHeight(float height) { View::SetLayoutHeight(height); return *this; } \
  /** \
  * @brief Sets the minimum width. \
  * \
  * @param[in] width The minimum width \
  */ \
  ChildClass& SetMinimumWidth(float width) { View::SetMinimumWidth(width); return *this; } \
  /** \
  * @brief Sets the minimum height. \
  * \
  * @param[in] height The minimum height \
  */ \
  ChildClass& SetMinimumHeight(float height) { View::SetMinimumHeight(height); return *this; } \
  /** \
  * @brief Sets the maximum width. \
  * \
  * @param[in] width The maximum width \
  */ \
  ChildClass& SetMaximumWidth(float width) { View::SetMaximumWidth(width); return *this; } \
  /** \
  * @brief Sets the maximum height. \
  * \
  * @param[in] height The maximum height \
  */ \
  ChildClass& SetMaximumHeight(float height) { View::SetMaximumHeight(height); return *this; } \
  /** \
  * @brief Sets the view margin. \
  * \
  * @param[in] margin The margin to set \
  */ \
  ChildClass& SetViewMargin(const Extents& margin) { View::SetViewMargin(margin); return *this; } \
  /** \
  * @brief Sets the view padding. \
  * \
  * @param[in] padding The padding to set \
  */ \
  ChildClass& SetViewPadding(const Extents& padding) { View::SetViewPadding(padding); return *this; } \
  /** \
  * @brief Sets the horizontal alignment within parent layout. \
  * \
  * @param[in] alignment The horizontal alignment \
  */ \
  ChildClass& SetHorizontalAlignment(LayoutAlignment alignment) { View::SetHorizontalAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the vertical alignment within parent layout. \
  * \
  * @param[in] alignment The vertical alignment \
  */ \
  ChildClass& SetVerticalAlignment(LayoutAlignment alignment) { View::SetVerticalAlignment(alignment); return *this; } \
  /** \
  * @brief Assigns this View instance to a target variable. \
  * This method is useful for capturing a reference to a View created within \
  * a declarative UI tree for later use. \
  */ \
  ChildClass& As(View& self) { View::As(self); return *this; } \
  /** \
  * @brief Executesa custom action on this View instance. \
  * Use this method to perform additional initialization or logic on a View \
  * without breaking the declarative method chaining. \
  * @param[in] action A function or lambda to be executed with this instance. \
  */ \
  ChildClass& With(std::function<void(View&)> action) { View::With(action); return *this; } \
  /** \
  * @brief Sets the background color. \
  * \
  * @param[in] color The required background color value \
  */ \
  ChildClass& SetBackgroundColor(const Vector4& color) { View::SetBackgroundColor(color); return *this; }
