// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_SELF_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the width of the View. \
  * \
  * @param[in] width The width to set \
  */ \
  ChildClass& SizeWidth(float width) { SetSizeWidth(width); return *this; } \
  /** \
  * @brief Sets the height of the View. \
  * \
  * @param[in] height The height to set \
  */ \
  ChildClass& SizeHeight(float height) { SetSizeHeight(height); return *this; } \
  /** \
  * @brief Sets the X position of the View. \
  * \
  * @param[in] x The X position to set \
  */ \
  ChildClass& PositionX(float x) { SetPositionX(x); return *this; } \
  /** \
  * @brief Sets the Y position of the View. \
  * \
  * @param[in] y The Y position to set \
  */ \
  ChildClass& PositionY(float y) { SetPositionY(y); return *this; } \
  /** \
  * @brief Sets the parent origin of the View. \
  * \
  * @param[in] point The parent origin to set \
  */ \
  ChildClass& ParentOrigin(const Vector3& point) { SetParentOrigin(point); return *this; } \
  /** \
  * @brief Sets the pivot point of the View. \
  * \
  * @param[in] point The pivot point to set \
  */ \
  ChildClass& PivotPoint(const Vector3& point) { SetPivotPoint(point); return *this; } \
  /** \
  * @brief Sets the layout width. \
  * \
  * Use LayoutDimension::WrapContent for content-based sizing, \
  * LayoutDimension::MatchParent to fill parent, or a positive value for fixed size. \
  * \
  * @param[in] width The layout width \
  */ \
  ChildClass& LayoutWidth(float width) { SetLayoutWidth(width); return *this; } \
  /** \
  * @brief Sets the layout height. \
  * \
  * @param[in] height The layout height \
  */ \
  ChildClass& LayoutHeight(float height) { SetLayoutHeight(height); return *this; } \
  /** \
  * @brief Sets the minimum width. \
  * \
  * @param[in] width The minimum width \
  */ \
  ChildClass& MinimumWidth(float width) { SetMinimumWidth(width); return *this; } \
  /** \
  * @brief Sets the minimum height. \
  * \
  * @param[in] height The minimum height \
  */ \
  ChildClass& MinimumHeight(float height) { SetMinimumHeight(height); return *this; } \
  /** \
  * @brief Sets the maximum width. \
  * \
  * @param[in] width The maximum width \
  */ \
  ChildClass& MaximumWidth(float width) { SetMaximumWidth(width); return *this; } \
  /** \
  * @brief Sets the maximum height. \
  * \
  * @param[in] height The maximum height \
  */ \
  ChildClass& MaximumHeight(float height) { SetMaximumHeight(height); return *this; } \
  /** \
  * @brief Sets the view margin. \
  * \
  * @param[in] margin The margin to set \
  */ \
  ChildClass& ViewMargin(const Extents& margin) { SetViewMargin(margin); return *this; } \
  /** \
  * @brief Sets the view padding. \
  * \
  * @param[in] padding The padding to set \
  */ \
  ChildClass& ViewPadding(const Extents& padding) { SetViewPadding(padding); return *this; } \
  /** \
  * @brief Sets the horizontal alignment within parent layout. \
  * \
  * @param[in] alignment The horizontal alignment \
  */ \
  ChildClass& HorizontalAlignment(LayoutAlignment alignment) { SetHorizontalAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the vertical alignment within parent layout. \
  * \
  * @param[in] alignment The vertical alignment \
  */ \
  ChildClass& VerticalAlignment(LayoutAlignment alignment) { SetVerticalAlignment(alignment); return *this; }

#define DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  DALI_UI_SELF_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Assigns this View instance to a target variable. \
  * This method is useful for capturing a reference to a View created within \
  * a declarative UI tree for later use. \
  */ \
  ChildClass& As(View& self) { View::As(self); return *this; } \
  /** \
  * @brief Executesa custom action on this View instance. \
  * Use this method to perform additional initialization or logic on a View \
  * without breaking the declarative method chaining. \
  * @param[in] action A function or lambda to be executed with this instance. \
  */ \
  ChildClass& With(std::function<void(View&)> action) { View::With(action); return *this; } \
  /** \
  * @brief Sets the background color. \
  * \
  * @param[in] color The required background color value \
  */ \
  ChildClass& BackgroundColor(const Vector4& color) { View::BackgroundColor(color); return *this; }
