// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_WEBVIEW_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the user agent string. \
  * \
  * @param[in] userAgent The user agent string \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetUserAgent(const Dali::String& userAgent) { WebView::SetUserAgent(userAgent); return *this; } \
  /** \
  * @brief Sets the page zoom factor. \
  * \
  * @param[in] zoomFactor The zoom factor \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPageZoomFactor(float zoomFactor) { WebView::SetPageZoomFactor(zoomFactor); return *this; } \
  /** \
  * @brief Sets the text zoom factor. \
  * \
  * @param[in] zoomFactor The zoom factor \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetTextZoomFactor(float zoomFactor) { WebView::SetTextZoomFactor(zoomFactor); return *this; } \
  /** \
  * @brief Sets whether mouse events are enabled. \
  * \
  * @param[in] enabled True to enable mouse events \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetMouseEventsEnabled(bool enabled) { WebView::SetMouseEventsEnabled(enabled); return *this; } \
  /** \
  * @brief Sets whether key events are enabled. \
  * \
  * @param[in] enabled True to enable key events \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetKeyEventsEnabled(bool enabled) { WebView::SetKeyEventsEnabled(enabled); return *this; } \
  /** \
  * @brief Sets whether video hole is enabled. \
  * \
  * @param[in] enabled True to enable video hole \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetVideoHoleEnabled(bool enabled) { WebView::SetVideoHoleEnabled(enabled); return *this; } \
  /** \
  * @brief Sets the document background color. \
  * \
  * @param[in] color The background color \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetDocumentBackgroundColor(const Dali::Vector4& color) { WebView::SetDocumentBackgroundColor(color); return *this; } \
  /** \
  * @brief Sets whether tiles are cleared when hidden. \
  * \
  * @param[in] cleared True to clear tiles when hidden \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetTilesClearedWhenHidden(bool cleared) { WebView::SetTilesClearedWhenHidden(cleared); return *this; } \
  /** \
  * @brief Sets the tile cover area multiplier. \
  * \
  * @param[in] multiplier The multiplier value \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetTileCoverAreaMultiplier(float multiplier) { WebView::SetTileCoverAreaMultiplier(multiplier); return *this; } \
  /** \
  * @brief Sets whether cursor is enabled by client. \
  * \
  * @param[in] enabled True to enable cursor by client \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetCursorEnabledByClient(bool enabled) { WebView::SetCursorEnabledByClient(enabled); return *this; }
