// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_ANIMATEDIMAGEVISUAL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VISUALBASE_METHODS(ChildClass) \
  /** \
  * @brief Sets the resource URL for a single image. \
  * \
  * This method cannot be used together with SetResourceUrlList; they are mutually exclusive. \
  * Use SetResourceUrl when you want to display a static image. \
  * \
  * @param[in] resourceUrl The resource URL to set \
  */ \
  ChildClass& SetResourceUrl(const Dali::String& resourceUrl) { AnimatedImageVisual::SetResourceUrl(resourceUrl); return *this; } \
  /** \
  * @brief Sets a list of resource URLs for an animated image sequence. \
  * \
  * @param[in] resourceUrlList The list of resource URLs to set \
  */ \
  ChildClass& SetResourceUrlList(const Dali::Vector<Dali::String>& resourceUrlList) { AnimatedImageVisual::SetResourceUrlList(resourceUrlList); return *this; } \
  /** \
  * @brief Sets a list of resource URLs for an animated image sequence. \
  * \
  * This method cannot be used together with SetResourceUrl; they are mutually exclusive. \
  * Provide multiple URLs to create an animation. \
  * \
  * @param[in] resourceUrlList The list of resource URLs to set \
  */ \
  ChildClass& SetResourceUrlList(std::initializer_list<Dali::String> resourceUrlList) { AnimatedImageVisual::SetResourceUrlList(resourceUrlList); return *this; } \
  /** \
  * @brief Sets whether the image is loaded synchronously. \
  * \
  * @param[in] synchronous True to load the image on the main thread synchronously \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSynchronousLoading(bool synchronous) { AnimatedImageVisual::SetSynchronousLoading(synchronous); return *this; } \
  /** \
  * @brief Sets the desired width of the AnimatedImageVisual. \
  * \
  * @param[in] desiredWidth The desired width to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetDesiredWidth(int desiredWidth) { AnimatedImageVisual::SetDesiredWidth(desiredWidth); return *this; } \
  /** \
  * @brief Sets the desired height of the AnimatedImageVisual. \
  * \
  * @param[in] desiredHeight The desired height to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetDesiredHeight(int desiredHeight) { AnimatedImageVisual::SetDesiredHeight(desiredHeight); return *this; } \
  /** \
  * @brief Sets the sampling mode of the AnimatedImageVisual. \
  * \
  * @param[in] samplingMode The sampling mode to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSamplingMode(Image::SamplingMode samplingMode) { AnimatedImageVisual::SetSamplingMode(samplingMode); return *this; } \
  /** \
  * @brief Sets the pixel area of the AnimatedImageVisual. \
  * \
  * @param[in] pixelArea The pixel area to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPixelArea(const Dali::Vector4& pixelArea) { AnimatedImageVisual::SetPixelArea(pixelArea); return *this; } \
  /** \
  * @brief Sets the wrap mode for u coordinate of the AnimatedImageVisual. \
  * \
  * @param[in] wrapModeU The wrap mode for u coordinate to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetWrapModeU(Dali::WrapMode::Type wrapModeU) { AnimatedImageVisual::SetWrapModeU(wrapModeU); return *this; } \
  /** \
  * @brief Sets the wrap mode for v coordinate of the AnimatedImageVisual. \
  * \
  * @param[in] wrapModeV The wrap mode for v coordinate to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetWrapModeV(Dali::WrapMode::Type wrapModeV) { AnimatedImageVisual::SetWrapModeV(wrapModeV); return *this; } \
  /** \
  * @brief Sets whether to enable broken image. \
  * \
  * @param[in] enableBrokenImage True to enable broken image \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetEnableBrokenImage(bool enableBrokenImage) { AnimatedImageVisual::SetEnableBrokenImage(enableBrokenImage); return *this; } \
  /** \
  * @brief Sets the load policy of the AnimatedImageVisual. \
  * \
  * @param[in] loadPolicy The load policy to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetLoadPolicy(Image::LoadPolicy loadPolicy) { AnimatedImageVisual::SetLoadPolicy(loadPolicy); return *this; } \
  /** \
  * @brief Sets the release policy of the AnimatedImageVisual. \
  * \
  * @param[in] releasePolicy The release policy to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetReleasePolicy(Image::ReleasePolicy releasePolicy) { AnimatedImageVisual::SetReleasePolicy(releasePolicy); return *this; } \
  /** \
  * @brief Sets the fitting mode of the AnimatedImageVisual. \
  * \
  * @param[in] fittingMode The fitting mode to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetFittingMode(Image::FittingMode fittingMode) { AnimatedImageVisual::SetFittingMode(fittingMode); return *this; } \
  /** \
  * @brief Sets whether to correct the image orientation. \
  * \
  * @param[in] orientationCorrection True to correct the image orientation \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetOrientationCorrection(bool orientationCorrection) { AnimatedImageVisual::SetOrientationCorrection(orientationCorrection); return *this; } \
  /** \
  * @brief Sets whether to use synchronous sizing. \
  * \
  * @param[in] synchronousSizing True to use synchronous sizing \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSynchronousSizing(bool synchronousSizing) { AnimatedImageVisual::SetSynchronousSizing(synchronousSizing); return *this; } \
  /** \
  * @brief Sets whether the image uses pre-multiplied alpha. \
  * \
  * @param[in] preMultiplied True if the image has pre-multiplied alpha \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPreMultipliedAlpha(bool preMultiplied) { AnimatedImageVisual::SetPreMultipliedAlpha(preMultiplied); return *this; } \
  /** \
  * @brief Sets the alpha mask url of the AnimatedImageVisual. \
  * \
  * @param[in] alphaMaskUrl The alpha mask url to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetAlphaMaskUrl(const Dali::String& alphaMaskUrl) { AnimatedImageVisual::SetAlphaMaskUrl(alphaMaskUrl); return *this; } \
  /** \
  * @brief Sets the mask content scale of the AnimatedImageVisual. \
  * \
  * @param[in] maskContentScale The mask content scale to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetMaskContentScale(float maskContentScale) { AnimatedImageVisual::SetMaskContentScale(maskContentScale); return *this; } \
  /** \
  * @brief Sets whether to crop to mask. \
  * \
  * @param[in] cropToMask True to crop to mask \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetCropToMask(bool cropToMask) { AnimatedImageVisual::SetCropToMask(cropToMask); return *this; } \
  /** \
  * @brief Sets the masking type of the AnimatedImageVisual. \
  * \
  * @param[in] maskingType The masking type to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetMaskingType(Image::MaskingType maskingType) { AnimatedImageVisual::SetMaskingType(maskingType); return *this; } \
  /** \
  * @brief Sets the loop count of the AnimatedImageVisual. \
  * \
  * @param[in] loopCount The loop count to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetLoopCount(int loopCount) { AnimatedImageVisual::SetLoopCount(loopCount); return *this; } \
  /** \
  * @brief Sets the play range of the AnimatedImageVisual. \
  * \
  * @param[in] playRange The play range to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPlayRange(const Dali::Property::Array& playRange) { AnimatedImageVisual::SetPlayRange(playRange); return *this; } \
  /** \
  * @brief Sets the stop behavior of the AnimatedImageVisual. \
  * \
  * @param[in] stopBehavior The stop behavior to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetStopBehavior(AnimatedImage::StopBehavior stopBehavior) { AnimatedImageVisual::SetStopBehavior(stopBehavior); return *this; } \
  /** \
  * @brief Sets the frame speed factor of the AnimatedImageVisual. \
  * \
  * @param[in] frameSpeedFactor The frame speed factor to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetFrameSpeedFactor(float frameSpeedFactor) { AnimatedImageVisual::SetFrameSpeedFactor(frameSpeedFactor); return *this; } \
  /** \
  * @brief Sets the batch size of the AnimatedImageVisual. \
  * \
  * @param[in] batchSize The batch size to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetBatchSize(int batchSize) { AnimatedImageVisual::SetBatchSize(batchSize); return *this; } \
  /** \
  * @brief Sets the cache size of the AnimatedImageVisual. \
  * \
  * @param[in] cacheSize The cache size to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetCacheSize(int cacheSize) { AnimatedImageVisual::SetCacheSize(cacheSize); return *this; } \
  /** \
  * @brief Sets the frame delay of the AnimatedImageVisual. \
  * \
  * This property is only relevant when using SetResourceUrlList (animated sequence). \
  * It specifies the delay between frames in milliseconds. \
  * \
  * @param[in] frameDelay The frame delay to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetFrameDelay(int frameDelay) { AnimatedImageVisual::SetFrameDelay(frameDelay); return *this; }
