// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_BORDERVISUAL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VISUALBASE_METHODS(ChildClass) \
  /** \
  * @brief Sets the size of border of the BorderVisual. \
  * \
  * @param[in] borderSize The size of border to set \
  */ \
  ChildClass& SetBorderSize(float borderSize) { BorderVisual::SetBorderSize(borderSize); return *this; } \
  /** \
  * @brief Sets the soft anti-aliasing enable of the BorderVisual. \
  * \
  * @param[in] enable True if soft anti-aliasing enabled \
  */ \
  ChildClass& SetEnableAntiAliasing(bool enable) { BorderVisual::SetEnableAntiAliasing(enable); return *this; }
