// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_COLORVISUAL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VISUALBASE_METHODS(ChildClass) \
  /** \
  * @brief Sets the blur radius of the ColorVisual. \
  * \
  * @param[in] blurRadius The blur radius to set \
  */ \
  ChildClass& SetBlurRadius(float blurRadius) { ColorVisual::SetBlurRadius(blurRadius); return *this; } \
  /** \
  * @brief Sets the cutout policy of the ColorVisual. \
  * \
  * @param[in] cutoutPolicy The cutout policy to set \
  */ \
  ChildClass& SetCutoutPolicy(CutoutPolicy cutoutPolicy) { ColorVisual::SetCutoutPolicy(cutoutPolicy); return *this; }
