// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_GRADIENTVISUAL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VISUALBASE_METHODS(ChildClass) \
  /** \
  * @brief Sets the start offset of the GradientVisual. \
  * \
  * @param[in] startOffset The start offset to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetStartOffset(float startOffset) { GradientVisual::SetStartOffset(startOffset); return *this; } \
  /** \
  * @brief Sets the start position of the GradientVisual. \
  * \
  * @param[in] startPosition The start position to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetStartPosition(const Dali::Vector2& startPosition) { GradientVisual::SetStartPosition(startPosition); return *this; } \
  /** \
  * @brief Sets the end position of the GradientVisual. \
  * \
  * @param[in] endPosition The end position to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetEndPosition(const Dali::Vector2& endPosition) { GradientVisual::SetEndPosition(endPosition); return *this; } \
  /** \
  * @brief Sets the center of the GradientVisual. \
  * \
  * @param[in] center The center to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetCenter(const Dali::Vector2& center) { GradientVisual::SetCenter(center); return *this; } \
  /** \
  * @brief Sets the radius of the GradientVisual. \
  * \
  * @param[in] radius The radius to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetRadius(float radius) { GradientVisual::SetRadius(radius); return *this; } \
  /** \
  * @brief Sets the start angle of the GradientVisual. \
  * \
  * @param[in] startAngle The start angle to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetStartAngle(Dali::Radian startAngle) { GradientVisual::SetStartAngle(startAngle); return *this; } \
  /** \
  * @brief Sets the stop nodes of the GradientVisual. \
  * @note Stop nodes must have at least 2 items. \
  * \
  * @param[in] stopOffset The stop nodes to set. \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetStopNodes(const Dali::Vector<Ui::Gradient::StopNode>& stopNodes) { GradientVisual::SetStopNodes(stopNodes); return *this; } \
  /** \
  * @brief Sets the stop nodes of the GradientVisual in a declarative way. \
  * This method allows for set stop nodes construction by passing \
  * a brace-enclosed initializer list of Gradient::StopNode objects. \
  * @note Stop nodes must have at least 2 items. \
  * \
  * @param[in] stopOffset The stop nodes to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetStopNodes(std::initializer_list<Ui::Gradient::StopNode> stopNodes) { GradientVisual::SetStopNodes(stopNodes); return *this; } \
  /** \
  * @brief Sets the gradient units of the GradientVisual. \
  * \
  * @param[in] gradientUnits The gradient units to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetUnits(Ui::Gradient::Units gradientUnits) { GradientVisual::SetUnits(gradientUnits); return *this; } \
  /** \
  * @brief Sets the spread method of the GradientVisual. \
  * \
  * @param[in] spreadMethod The spread method to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSpreadMethod(Ui::Gradient::SpreadMethod spreadMethod) { GradientVisual::SetSpreadMethod(spreadMethod); return *this; }
