// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_IMAGEVISUAL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VISUALBASE_METHODS(ChildClass) \
  /** \
  * @brief Sets the resource url of the ImageVisual. \
  * \
  * @param[in] resourceUrl The resource url to set \
  */ \
  ChildClass& SetResourceUrl(const Dali::String& resourceUrl) { ImageVisual::SetResourceUrl(resourceUrl); return *this; } \
  /** \
  * @brief Sets whether the image is loaded synchronously. \
  * \
  * @param[in] synchronous True to load the image on the main thread synchronously \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSynchronousLoading(bool synchronous) { ImageVisual::SetSynchronousLoading(synchronous); return *this; } \
  /** \
  * @brief Sets the desired width of the ImageVisual. \
  * \
  * @param[in] desiredWidth The desired width to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetDesiredWidth(int desiredWidth) { ImageVisual::SetDesiredWidth(desiredWidth); return *this; } \
  /** \
  * @brief Sets the desired height of the ImageVisual. \
  * \
  * @param[in] desiredHeight The desired height to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetDesiredHeight(int desiredHeight) { ImageVisual::SetDesiredHeight(desiredHeight); return *this; } \
  /** \
  * @brief Sets the sampling mode of the ImageVisual. \
  * \
  * @param[in] samplingMode The sampling mode to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSamplingMode(Image::SamplingMode samplingMode) { ImageVisual::SetSamplingMode(samplingMode); return *this; } \
  /** \
  * @brief Sets the pixel area of the ImageVisual. \
  * \
  * @param[in] pixelArea The pixel area to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPixelArea(const Dali::Vector4& pixelArea) { ImageVisual::SetPixelArea(pixelArea); return *this; } \
  /** \
  * @brief Sets the wrap mode for u coordinate of the ImageVisual. \
  * \
  * @param[in] wrapModeU The wrap mode for u coordinate to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetWrapModeU(Dali::WrapMode::Type wrapModeU) { ImageVisual::SetWrapModeU(wrapModeU); return *this; } \
  /** \
  * @brief Sets the wrap mode for v coordinate of the ImageVisual. \
  * \
  * @param[in] wrapModeV The wrap mode for v coordinate to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetWrapModeV(Dali::WrapMode::Type wrapModeV) { ImageVisual::SetWrapModeV(wrapModeV); return *this; } \
  /** \
  * @brief Sets whether to enable broken image. \
  * \
  * @param[in] enableBrokenImage True to enable broken image \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetEnableBrokenImage(bool enableBrokenImage) { ImageVisual::SetEnableBrokenImage(enableBrokenImage); return *this; } \
  /** \
  * @brief Sets the load policy of the ImageVisual. \
  * \
  * @param[in] loadPolicy The load policy to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetLoadPolicy(Image::LoadPolicy loadPolicy) { ImageVisual::SetLoadPolicy(loadPolicy); return *this; } \
  /** \
  * @brief Sets the release policy of the ImageVisual. \
  * \
  * @param[in] releasePolicy The release policy to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetReleasePolicy(Image::ReleasePolicy releasePolicy) { ImageVisual::SetReleasePolicy(releasePolicy); return *this; } \
  /** \
  * @brief Sets the fitting mode of the ImageVisual. \
  * \
  * @param[in] fittingMode The fitting mode to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetFittingMode(Image::FittingMode fittingMode) { ImageVisual::SetFittingMode(fittingMode); return *this; } \
  /** \
  * @brief Sets whether to correct the image orientation. \
  * \
  * @param[in] orientationCorrection True to correct the image orientation \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetOrientationCorrection(bool orientationCorrection) { ImageVisual::SetOrientationCorrection(orientationCorrection); return *this; } \
  /** \
  * @brief Sets whether to use synchronous sizing. \
  * \
  * @param[in] synchronousSizing True to use synchronous sizing \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSynchronousSizing(bool synchronousSizing) { ImageVisual::SetSynchronousSizing(synchronousSizing); return *this; } \
  /** \
  * @brief Sets whether to use fast track uploading. \
  * \
  * @param[in] fastTrackUploading True to use fast track uploading \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetFastTrackUploading(bool fastTrackUploading) { ImageVisual::SetFastTrackUploading(fastTrackUploading); return *this; } \
  /** \
  * @brief Sets the NPatch border of the ImageVisual. \
  * \
  * @param[in] border The NPatch border to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetNPatchBorder(const Dali::Extents& border) { ImageVisual::SetNPatchBorder(border); return *this; } \
  /** \
  * @brief Sets whether to draw only the borders. \
  * \
  * @param[in] borderOnly True to draw only the borders \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetNPatchBorderOnly(bool borderOnly) { ImageVisual::SetNPatchBorderOnly(borderOnly); return *this; } \
  /** \
  * @brief Sets the auxiliary image url of the ImageVisual. \
  * @note Only available if resource is n-patch, or NpatchBorder applied. \
  * \
  * @param[in] auxiliaryImage The auxiliary image url to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetNPatchAuxiliaryImage(const Dali::String& auxiliaryImage) { ImageVisual::SetNPatchAuxiliaryImage(auxiliaryImage); return *this; } \
  /** \
  * @brief Sets the auxiliary image alpha of the ImageVisual. \
  * @note Only available if resource is n-patch, or NpatchBorder applied. \
  * \
  * @param[in] auxiliaryImageAlpha The auxiliary image alpha to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetNPatchAuxiliaryImageAlpha(float auxiliaryImageAlpha) { ImageVisual::SetNPatchAuxiliaryImageAlpha(auxiliaryImageAlpha); return *this; } \
  /** \
  * @brief Sets whether the image uses pre-multiplied alpha. \
  * \
  * @param[in] preMultiplied True if the image has pre-multiplied alpha \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPreMultipliedAlpha(bool preMultiplied) { ImageVisual::SetPreMultipliedAlpha(preMultiplied); return *this; } \
  /** \
  * @brief Sets the alpha mask url of the ImageVisual. \
  * \
  * @param[in] alphaMaskUrl The alpha mask url to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetAlphaMaskUrl(const Dali::String& alphaMaskUrl) { ImageVisual::SetAlphaMaskUrl(alphaMaskUrl); return *this; } \
  /** \
  * @brief Sets the mask content scale of the ImageVisual. \
  * \
  * @param[in] maskContentScale The mask content scale to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetMaskContentScale(float maskContentScale) { ImageVisual::SetMaskContentScale(maskContentScale); return *this; } \
  /** \
  * @brief Sets whether to crop to mask. \
  * \
  * @param[in] cropToMask True to crop to mask \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetCropToMask(bool cropToMask) { ImageVisual::SetCropToMask(cropToMask); return *this; } \
  /** \
  * @brief Sets the masking type of the ImageVisual. \
  * \
  * @param[in] maskingType The masking type to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetMaskingType(Image::MaskingType maskingType) { ImageVisual::SetMaskingType(maskingType); return *this; }
