// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_TEXTVISUAL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VISUALBASE_METHODS(ChildClass) \
  /** \
  * @brief Sets the text to display. \
  * \
  * @param[in] text The text to display in UTF-8 format. \
  */ \
  ChildClass& SetText(const Dali::String& text) { TextVisual::SetText(text); return *this; } \
  /** \
  * @brief Sets the font family to use. \
  * \
  * @param[in] fontFamily The requested font family to use \
  */ \
  ChildClass& SetFontFamily(const Dali::String& fontFamily) { TextVisual::SetFontFamily(fontFamily); return *this; } \
  /** \
  * @brief Sets the size of font in pixels. \
  * \
  * @param[in] fontSize The size of font in pixels \
  */ \
  ChildClass& SetFontSize(float fontSize) { TextVisual::SetFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets the font weight. \
  * \
  * @param[in] fontWeight The font weight to set \
  */ \
  ChildClass& SetFontWeight(Dali::Ui::Text::FontWeight fontWeight) { TextVisual::SetFontWeight(fontWeight); return *this; } \
  /** \
  * @brief Sets the font width. \
  * \
  * @param[in] fontWidth The font width to set \
  */ \
  ChildClass& SetFontWidth(Dali::Ui::Text::FontWidth fontWidth) { TextVisual::SetFontWidth(fontWidth); return *this; } \
  /** \
  * @brief Sets the font slant. \
  * \
  * @param[in] fontSlant The font slant to set \
  */ \
  ChildClass& SetFontSlant(Dali::Ui::Text::FontSlant fontSlant) { TextVisual::SetFontSlant(fontSlant); return *this; } \
  /** \
  * @brief Sets the single-line or multi-line layout option. \
  * \
  * @param[in] multiLine True to enable multi-line layout, false for single-line \
  */ \
  ChildClass& SetMultiLine(bool multiLine) { TextVisual::SetMultiLine(multiLine); return *this; } \
  /** \
  * @brief Sets the line wrap mode. \
  * \
  * @param[in] lineWrapMode The line wrap mode to set \
  */ \
  ChildClass& SetLineWrapMode(Dali::Ui::Text::LineWrapMode lineWrapMode) { TextVisual::SetLineWrapMode(lineWrapMode); return *this; } \
  /** \
  * @brief Sets the horizontal alignment. \
  * \
  * @param[in] alignment The horizontal alignment to set \
  */ \
  ChildClass& SetHorizontalAlignment(Dali::Ui::Text::Alignment alignment) { TextVisual::SetHorizontalAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the vertical alignment. \
  * \
  * @param[in] alignment The vertical alignment to set \
  */ \
  ChildClass& SetVerticalAlignment(Dali::Ui::Text::Alignment alignment) { TextVisual::SetVerticalAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the overflow mode. \
  * \
  * @param[in] overflowMode The overflow mode to set \
  */ \
  ChildClass& SetOverflowMode(Dali::Ui::Text::OverflowMode overflowMode) { TextVisual::SetOverflowMode(overflowMode); return *this; } \
  /** \
  * @brief Sets the line height. \
  * \
  * @param[in] lineHeight The line height to set \
  */ \
  ChildClass& SetLineHeight(float lineHeight) { TextVisual::SetLineHeight(lineHeight); return *this; } \
  /** \
  * @brief Sets the line height mode. \
  * \
  * @param[in] lineHeightMode The line height mode to set \
  */ \
  ChildClass& SetLineHeightMode(Dali::Ui::Text::LineHeightMode lineHeightMode) { TextVisual::SetLineHeightMode(lineHeightMode); return *this; } \
  /** \
  * @brief Sets the color of the text. \
  * \
  * @param[in] textColor The color of the text \
  */ \
  ChildClass& SetTextColor(const UiColor& textColor) { TextVisual::SetTextColor(textColor); return *this; } \
  /** \
  * @brief Sets whether the mark-up processing is enabled. \
  * \
  * @param[in] enabled True to enable mark-up processing \
  */ \
  ChildClass& SetMarkupEnabled(bool enabled) { TextVisual::SetMarkupEnabled(enabled); return *this; } \
  /** \
  * @brief Sets whether  the text is rendered as a cutout. \
  * \
  * When enabled, the glyph shapes are cut out from the rendered content \
  * instead of being filled with the text color. \
  * \
  * @param[in] enabled True to render the text as a cutout, false to render it normally. \
  */ \
  ChildClass& SetCutoutEnabled(bool enabled) { TextVisual::SetCutoutEnabled(enabled); return *this; }
