// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_VISUALBASE_METHODS(ChildClass) \
  /** \
  * @brief Sets the name of this VisualBase. \
  * \
  * @param[in] name The name to set \
  */ \
  ChildClass& SetName(const Dali::String& name) { VisualBase::SetName(name); return *this; } \
  /** \
  * @brief Sets the color of this VisualBase. \
  * \
  * @param[in] color The UiColor to apply \
  */ \
  ChildClass& SetColor(const UiColor& color) { VisualBase::SetColor(color); return *this; } \
  /** \
  * @brief Sets the X offset of the VisualBase. \
  * \
  * @param[in] x The X offset to set \
  */ \
  ChildClass& SetOffsetX(float x) { VisualBase::SetOffsetX(x); return *this; } \
  /** \
  * @brief Sets the Y offset of the VisualBase. \
  * \
  * @param[in] y The Y offset to set \
  */ \
  ChildClass& SetOffsetY(float y) { VisualBase::SetOffsetY(y); return *this; } \
  /** \
  * @brief Sets the width of the VisualBase. \
  * \
  * @param[in] width The width to set \
  */ \
  ChildClass& SetWidth(float width) { VisualBase::SetWidth(width); return *this; } \
  /** \
  * @brief Sets the height of the VisualBase. \
  * \
  * @param[in] height The height to set \
  */ \
  ChildClass& SetHeight(float height) { VisualBase::SetHeight(height); return *this; } \
  /** \
  * @brief Sets the proportion flags of the VisualBase. \
  * \
  * @param[in] flags The proportion flags to set \
  */ \
  ChildClass& SetProportionFlags(Dali::Ui::Visual::Transform::ProportionFlags flags) { VisualBase::SetProportionFlags(flags); return *this; } \
  /** \
  * @brief Sets the extra width of the VisualBase. \
  * This width will be added to final width absolutly, independent as proportion flags. \
  * \
  * @param[in] extraWidth The extra width to set \
  */ \
  ChildClass& SetExtraWidth(float extraWidth) { VisualBase::SetExtraWidth(extraWidth); return *this; } \
  /** \
  * @brief Sets the extra height of the VisualBase. \
  * This height will be added to final height absolutly, independent as proportion flags. \
  * \
  * @param[in] extraHeight The extra height to set \
  */ \
  ChildClass& SetExtraHeight(float extraHeight) { VisualBase::SetExtraHeight(extraHeight); return *this; } \
  /** \
  * @brief Sets the origin of the VisualBase. \
  * \
  * @param[in] origin The origin type to set \
  */ \
  ChildClass& SetOrigin(Align::Type origin) { VisualBase::SetOrigin(origin); return *this; } \
  /** \
  * @brief Sets the pivot of the VisualBase. \
  * \
  * @param[in] pivot The pivot to set \
  */ \
  ChildClass& SetPivot(Align::Type pivot) { VisualBase::SetPivot(pivot); return *this; } \
  /** \
  * @brief Sets a uniform corner radius for all four corners. \
  * @note Only supported type of visual has efforts. \
  * \
  * @param[in] radius The corner radius to apply to all corners \
  */ \
  ChildClass& SetCornerRadius(float radius) { VisualBase::SetCornerRadius(radius); return *this; } \
  /** \
  * @brief Sets individual corner radii for all four corners. \
  * @note Only supported type of visual has efforts. \
  * \
  * @param[in] topLeft     The radius for the top-left corner \
  * @param[in] topRight    The radius for the top-right corner \
  * @param[in] bottomRight The radius for the bottom-right corner \
  * @param[in] bottomLeft  The radius for the bottom-left corner \
  */ \
  ChildClass& SetCornerRadius(float topLeft, float topRight, float bottomRight, float bottomLeft) { VisualBase::SetCornerRadius(topLeft, topRight, bottomRight, bottomLeft); return *this; } \
  /** \
  * @brief Sets corner radii from a Vector4. \
  * @note Only supported type of visual has efforts. \
  * \
  * @param[in] radius Corner radii as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft) \
  */ \
  ChildClass& SetCornerRadius(const Vector4& radius) { VisualBase::SetCornerRadius(radius); return *this; } \
  /** \
  * @brief Sets the corner radius policy. \
  * @note Only supported type of visual has efforts. \
  * \
  * @param[in] policy ABSOLUTE for world-unit values (default), RELATIVE for percentage [0.0, 0.5] of the shorter side \
  */ \
  ChildClass& SetCornerRadiusPolicy(CornerRadiusPolicy policy) { VisualBase::SetCornerRadiusPolicy(policy); return *this; } \
  /** \
  * @brief Shortcut to set the corner radius policy to RELATIVE. \
  * @note Only supported type of visual has efforts. \
  * \
  * Equivalent to SetCornerRadiusPolicy(CornerRadiusPolicy::RELATIVE). \
  */ \
  ChildClass& SetCornerRadiusPolicyRelative() { VisualBase::SetCornerRadiusPolicyRelative(); return *this; } \
  /** \
  * @brief Sets a uniform corner squareness for all four corners. \
  * @note Only supported type of visual has efforts. \
  * \
  * @param[in] squareness The squareness value to apply to all corners \
  */ \
  ChildClass& SetCornerSquareness(float squareness) { VisualBase::SetCornerSquareness(squareness); return *this; } \
  /** \
  * @brief Sets individual corner squareness values for all four corners. \
  * @note Only supported type of visual has efforts. \
  * \
  * @param[in] topLeft     The squareness for the top-left corner \
  * @param[in] topRight    The squareness for the top-right corner \
  * @param[in] bottomRight The squareness for the bottom-right corner \
  * @param[in] bottomLeft  The squareness for the bottom-left corner \
  */ \
  ChildClass& SetCornerSquareness(float topLeft, float topRight, float bottomRight, float bottomLeft) { VisualBase::SetCornerSquareness(topLeft, topRight, bottomRight, bottomLeft); return *this; } \
  /** \
  * @brief Sets corner squareness from a Vector4. \
  * @note Only supported type of visual has efforts. \
  * \
  * @param[in] squareness Squareness values as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft) \
  */ \
  ChildClass& SetCornerSquareness(const Vector4& squareness) { VisualBase::SetCornerSquareness(squareness); return *this; } \
  /** \
  * @brief Sets the borderline width of the VisualBase. \
  * @note Only supported type of visual has efforts. \
  * \
  * @param[in] width The borderline width to set \
  */ \
  ChildClass& SetBorderlineWidth(float width) { VisualBase::SetBorderlineWidth(width); return *this; } \
  /** \
  * @brief Sets the borderline color of the VisualBase. \
  * @note Only supported type of visual has efforts. \
  * \
  * If the UiColor has a color ID, it is resolved from the current \
  * theme and a binding is registered so the color is automatically \
  * refreshed when the theme changes. \
  * \
  * @param[in] color The UiColor to apply \
  */ \
  ChildClass& SetBorderlineColor(const UiColor& color) { VisualBase::SetBorderlineColor(color); return *this; } \
  /** \
  * @brief Sets the borderline offset of the VisualBase. \
  * @note Only supported type of visual has efforts. \
  * \
  * @param[in] offset The borderline offset to set \
  */ \
  ChildClass& SetBorderlineOffset(float offset) { VisualBase::SetBorderlineOffset(offset); return *this; } \
  /** \
  * @brief Assigns this VisualBase instance to a target variable. \
  * This method is useful for capturing a reference to a VisualBase created within \
  * a declarative UI tree for later use. \
  */ \
  ChildClass& As(VisualBase& self) { VisualBase::As(self); return *this; } \
  /** \
  * @brief Executes a custom action on this View instance. \
  * \
  * Useful for performing additional setup (e.g. signal connections, \
  * predefined style application) without breaking the method chain. \
  * \
  * @param[in] action A callable (lambda or free function) invoked with \
  *                   a reference to this instance. \
  * \
  * @return Reference to this View for fluent chaining. \
  */ \
  template<typename F> \
  ChildClass& With(F&& action) \
  { \
  action(*this); \
  return *this; \
  }
