/* Copyright (c) 2026 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

// No DALi dependency: these algorithms are tested with synthetic pixels, not
// with output generated by the renderer being tested. Coordinates are capture
// pixels, rectangles are half-open, and images are tightly packed RGBA8.
namespace TextManualTest::ImageCheck
{
struct Color
{
  uint8_t r{255}, g{255}, b{255}, a{255};
};

struct Rect
{
  int x{0}, y{0}, width{0}, height{0};
};

struct Image
{
  uint32_t             width{0}, height{0};
  std::vector<uint8_t> rgba;
  bool                 IsValid() const;
  Color                At(uint32_t x, uint32_t y) const;
};

// Rejects unsupported size/stride/truncated input; does not silently resize,
// flip, resample or align an image to make a comparison pass.
bool        Decode(const uint8_t* bytes, std::size_t byteCount, uint32_t width, uint32_t height,
                   uint32_t channels, Image& output, std::string& error, bool blueFirst = false);
bool        Contains(const Image& image, Rect region);
Image       Crop(const Image& image, Rect region);
std::size_t CountColor(const Image& image, Rect region, Color color, uint8_t tolerance = 16);
Rect        ColorBounds(const Image& image, Rect region, Color color, uint8_t tolerance = 16);
std::size_t CountInk(const Image& image, Rect region, Color background = {}, uint8_t threshold = 32);

struct CompareOptions
{
  Color       background{};
  uint8_t     channelTolerance{16};
  uint8_t     inkThreshold{32};
  double      maximumChangedFraction{0.001};
  std::size_t maximumChangedPixels{4};
  std::size_t minimumInkPixels{12};
};

struct Comparison
{
  bool        valid{false}, equal{false};
  std::size_t changedPixels{0}, inkPixels{0};
  double      changedFraction{0.0};
  std::string error;
  std::string Describe() const;
};

// The denominator is the UNION of foreground pixels, not the entire white
// viewport. Blank images are not evidence of correct text rendering.
Comparison Compare(const Image& expected, const Image& actual, Rect region, CompareOptions options = {});
Image      Difference(const Image& expected, const Image& actual, uint8_t tolerance = 16);

struct Translation
{
  bool   valid{false};
  int    dx{0}, dy{0}; // actual content position minus reference content position
  double mismatch{1.0};
};

// A diagnostic motion estimate, not an alignment step for Compare(). Assumes
// an opaque white background. Rejects blank/low-information overlap.
Translation EstimateTranslation(const Image& reference, const Image& actual, Rect region,
                                int maximumX, int maximumY, std::size_t minimumInkPixels = 40);
// PNG I/O is optional. TEXT_PIXEL_CHECKS=OFF leaves the algorithms available
// but makes these functions return false with an explicit error.
bool SavePng(const Image& image, const std::string& path, std::string& error);
bool LoadPng(const std::string& path, Image& image, std::string& error);
} // namespace TextManualTest::ImageCheck
