#pragma once

// --- DALI_UI_CHAIN_MACROS_START ---
// Generated by dali-ui preprocessor. Do not modify.
#define DALI_UI_CHAIN_APPBAR_METHODS(ChildClass) DALI_UI_CHAIN_VIEW_METHODS(ChildClass)

// --- DALI_UI_CHAIN_MACROS_END ---

/*
 * Copyright (c) 2026 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// EXTERNAL INCLUDES
#include <dali-ui-foundation/public-api/view.h>

// INTERNAL INCLUDES

namespace Dali
{

namespace UI
{

// Forward declarations
namespace Internal
{
class AppBarImpl;
}

#include "app-bar.autogen.h"
/**
 * @brief AppBar shows title text and provides navigation and action functions on Page.
 */
class DALI_UI_API AppBar : public View
{
public:

  // Typedefs

public: // Creation & Destruction

  /**
   * @brief Creates an uninitialized AppBar handle.
   */
  AppBar();

  /**
   * @brief Creates an initialized AppBar.
   */
  static AppBar New();

  /**
   * @brief Copy constructor.
   */
  AppBar(const AppBar& appBar);

  /**
   * @brief Move constructor.
   */
  AppBar(AppBar&& rhs) noexcept;

  /**
   * @brief Virtual destructor.
   */
  ~AppBar();

public: // Operators

  AppBar& operator=(const AppBar& handle);
  AppBar& operator=(AppBar&& rhs) noexcept;

public: // Static Methods

  /**
   * @brief Downcasts a handle to AppBar handle.
   */
  static AppBar DownCast(BaseHandle handle);

public: // Setters for chaining

  // @CHAIN_START(AppBar, View)
  // @CHAIN_END

public: // Signals

public: // Not intended for application developers

  /// @cond internal
  DALI_INTERNAL AppBar(Internal::AppBarImpl& implementation);
  explicit DALI_INTERNAL AppBar(Dali::Internal::CustomActor* internal);
  /// @endcond

public:
  DALI_UI_CHAIN_VIEW_METHODS(AppBar)
};

} // namespace UI

} // namespace Dali
