#pragma once

// --- DALI_UI_CHAIN_MACROS_START ---
// Generated by dali-ui preprocessor. Do not modify.
#define DALI_UI_CHAIN_CONTENTPAGE_METHODS(ChildClass) DALI_UI_CHAIN_PAGE_METHODS(ChildClass)

// --- DALI_UI_CHAIN_MACROS_END ---

/*
 * Copyright (c) 2026 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// EXTERNAL INCLUDES
#include <dali-ui-components/public-api/page.h>

// INTERNAL INCLUDES

namespace Dali
{

namespace UI
{

// Forward declarations
namespace Internal
{
class ContentPageImpl;
}

#include "content-page.autogen.h"
/**
 * @brief ContentPage is a formatted full-screen page containing an AppBar and content.
 */
class DALI_UI_API ContentPage : public Page
{
public:

  // Typedefs

public: // Creation & Destruction

  /**
   * @brief Creates an uninitialized ContentPage handle.
   */
  ContentPage();

  /**
   * @brief Creates an initialized ContentPage.
   */
  static ContentPage New();

  /**
   * @brief Copy constructor.
   */
  ContentPage(const ContentPage& contentPage);

  /**
   * @brief Move constructor.
   */
  ContentPage(ContentPage&& rhs) noexcept;

  /**
   * @brief Virtual destructor.
   */
  ~ContentPage();

public: // Operators

  ContentPage& operator=(const ContentPage& handle);
  ContentPage& operator=(ContentPage&& rhs) noexcept;

public: // Static Methods

  /**
   * @brief Downcasts a handle to ContentPage handle.
   */
  static ContentPage DownCast(BaseHandle handle);

public: // Setters for chaining

  // @CHAIN_START(ContentPage, Page)
  // @CHAIN_END

public: // Signals

public: // Not intended for application developers

  /// @cond internal
  DALI_INTERNAL ContentPage(Internal::ContentPageImpl& implementation);
  explicit DALI_INTERNAL ContentPage(Dali::Internal::CustomActor* internal);
  /// @endcond

public:
  DALI_UI_CHAIN_PAGE_METHODS(ContentPage)
};

} // namespace UI

} // namespace Dali
