#pragma once

// --- DALI_UI_CHAIN_MACROS_START ---
// Generated by dali-ui preprocessor. Do not modify.
#define DALI_UI_CHAIN_DIALOGPAGE_METHODS(ChildClass) DALI_UI_CHAIN_PAGE_METHODS(ChildClass)

// --- DALI_UI_CHAIN_MACROS_END ---

/*
 * Copyright (c) 2026 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// EXTERNAL INCLUDES
#include <dali-ui-components/public-api/page.h>

// INTERNAL INCLUDES

namespace Dali
{

namespace UI
{

// Forward declarations
namespace Internal
{
class DialogPageImpl;
}

#include "dialog-page.autogen.h"
/**
 * @brief DialogPage shows a dialog on the page with a dimmed scrim.
 */
class DALI_UI_API DialogPage : public Page
{
public:

  // Typedefs

public: // Creation & Destruction

  /**
   * @brief Creates an uninitialized DialogPage handle.
   */
  DialogPage();

  /**
   * @brief Creates an initialized DialogPage.
   */
  static DialogPage New();

  /**
   * @brief Copy constructor.
   */
  DialogPage(const DialogPage& dialogPage);

  /**
   * @brief Move constructor.
   */
  DialogPage(DialogPage&& rhs) noexcept;

  /**
   * @brief Virtual destructor.
   */
  ~DialogPage();

public: // Operators

  DialogPage& operator=(const DialogPage& handle);
  DialogPage& operator=(DialogPage&& rhs) noexcept;

public: // Static Methods

  /**
   * @brief Downcasts a handle to DialogPage handle.
   */
  static DialogPage DownCast(BaseHandle handle);

public: // Setters for chaining

  // @CHAIN_START(DialogPage, Page)
  // @CHAIN_END

public: // Signals

public: // Not intended for application developers

  /// @cond internal
  DALI_INTERNAL DialogPage(Internal::DialogPageImpl& implementation);
  explicit DALI_INTERNAL DialogPage(Dali::Internal::CustomActor* internal);
  /// @endcond

public:
  DALI_UI_CHAIN_PAGE_METHODS(DialogPage)
};

} // namespace UI

} // namespace Dali
