// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_SELF_DUMMYCOMPONENT_METHODS(ChildClass) \

#define DALI_UI_CHAIN_DUMMYCOMPONENT_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  DALI_UI_SELF_DUMMYCOMPONENT_METHODS(ChildClass)
