#pragma once

// --- DALI_UI_CHAIN_MACROS_START ---
// Generated by dali-ui preprocessor. Do not modify.
#define DALI_UI_CHAIN_NAVIGATOR_METHODS(ChildClass) DALI_UI_CHAIN_VIEW_METHODS(ChildClass)

// --- DALI_UI_CHAIN_MACROS_END ---

/*
 * Copyright (c) 2026 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// EXTERNAL INCLUDES
#include <dali-ui-foundation/public-api/view.h>
#include <dali-ui-foundation/public-api/dali-ui-common.h>

// INTERNAL INCLUDES
#include <dali-ui-components/public-api/page.h>

namespace Dali
{

namespace UI
{

// Forward declarations
namespace Internal
{
class NavigatorImpl;
}

#include "navigator.autogen.h"
/**
 * @brief Navigator navigates pages with stack methods.
 */
class DALI_UI_API Navigator : public View
{
public:

  // Typedefs

public: // Creation & Destruction

  /**
   * @brief Creates an uninitialized Navigator handle.
   */
  Navigator();

  /**
   * @brief Creates an initialized Navigator.
   *
   * @return A handle to a newly allocated Dali resource
   */
  static Navigator New();

  /**
   * @brief Copy constructor.
   *
   * @param[in] navigator Handle to copy
   */
  Navigator(const Navigator& navigator);

  /**
   * @brief Move constructor.
   *
   * @param[in] rhs Handle to move
   */
  Navigator(Navigator&& rhs) noexcept;

  /**
   * @brief Virtual destructor.
   */
  ~Navigator();

public: // Operators

  /**
   * @brief Copy assignment operator.
   */
  Navigator& operator=(const Navigator& handle);

  /**
   * @brief Move assignment operator.
   */
  Navigator& operator=(Navigator&& rhs) noexcept;

public: // Static Methods

  /**
   * @brief Downcasts a handle to Navigator handle.
   */
  static Navigator DownCast(BaseHandle handle);

public: // Methods

  /**
   * @brief Pushes a page to the navigator.
   * @param page The page to push.
   */
  void Push(Page page);

  /**
   * @brief Pops the top page from the navigator.
   * @return The popped page.
   */
  Page Pop();

  /**
   * @brief Inserts a page into the navigator at the specified index.
   * @param page The page to insert.
   * @param index The index to insert at.
   */
  void Insert(Page page, uint32_t index);

  /**
   * @brief Removes a page from the navigator.
   * @param page The page to remove.
   */
  void Remove(Page page);

  /**
   * @brief Gets the page at the specified index.
   * @param index The index of the page.
   * @return The page at the index.
   */
  Page GetPage(uint32_t index) const;

  /**
   * @brief Gets the number of pages in the navigator.
   * @return The page count.
   */
  uint32_t GetPageCount() const;

public: // Setters for chaining

  // @CHAIN_START(Navigator, View)
  // @CHAIN_END

public: // Signals

public: // Not intended for application developers

  /// @cond internal
  /**
   * @brief Creates a handle using the Internal implementation.
   */
  DALI_INTERNAL Navigator(Internal::NavigatorImpl& implementation);

  /**
   * @brief Allows the creation of this Control from an Internal::CustomActor pointer.
   */
  explicit DALI_INTERNAL Navigator(Dali::Internal::CustomActor* internal);
  /// @endcond

public:
  DALI_UI_CHAIN_VIEW_METHODS(Navigator)
};

} // namespace UI

} // namespace Dali
