#pragma once

// --- DALI_UI_CHAIN_MACROS_START ---
// Generated by dali-ui preprocessor. Do not modify.
#define DALI_UI_CHAIN_PAGE_METHODS(ChildClass) DALI_UI_CHAIN_VIEW_METHODS(ChildClass)

// --- DALI_UI_CHAIN_MACROS_END ---

/*
 * Copyright (c) 2026 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// EXTERNAL INCLUDES
#include <dali-ui-foundation/public-api/view.h>
#include <dali-ui-foundation/public-api/dali-ui-common.h>

// INTERNAL INCLUDES

namespace Dali
{

namespace UI
{

// Forward declarations
namespace Internal
{
class PageImpl;
}

#include "page.autogen.h"
/**
 * @brief Page is an element of navigation.
 */
class DALI_UI_API Page : public View
{
public:

  // Typedefs

public: // Creation & Destruction

  /**
   * @brief Creates an uninitialized Page handle.
   */
  Page();

  /**
   * @brief Creates an initialized Page.
   *
   * @return A handle to a newly allocated Dali resource
   */
  static Page New();

  /**
   * @brief Copy constructor.
   *
   * Creates another handle that points to the same real object.
   * @param[in] page Handle to copy
   */
  Page(const Page& page);

  /**
   * @brief Move constructor.
   *
   * @param[in] rhs Handle to move
   */
  Page(Page&& rhs) noexcept;

  /**
   * @brief Virtual destructor.
   */
  ~Page();

public: // Operators

  /**
   * @brief Copy assignment operator.
   */
  Page& operator=(const Page& handle);

  /**
   * @brief Move assignment operator.
   */
  Page& operator=(Page&& rhs) noexcept;

public: // Static Methods

  /**
   * @brief Downcasts a handle to Page handle.
   */
  static Page DownCast(BaseHandle handle);

public: // Setters for chaining

  // @CHAIN_START(Page, View)
  // @CHAIN_END

public: // Signals

public: // Not intended for application developers

  /// @cond internal
  /**
   * @brief Creates a handle using the Internal implementation.
   */
  DALI_INTERNAL Page(Internal::PageImpl& implementation);

  /**
   * @brief Allows the creation of this Control from an Internal::CustomActor pointer.
   */
  explicit DALI_INTERNAL Page(Dali::Internal::CustomActor* internal);
  /// @endcond

public:
  DALI_UI_CHAIN_VIEW_METHODS(Page)
};

} // namespace UI

} // namespace Dali
