#!/usr/bin/env python3
#
# Copyright (c) 2026 Samsung Electronics Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import argparse
import hashlib
import re
import sys
from collections import Counter, OrderedDict
from pathlib import Path
from urllib.request import urlopen


UNICODE_EMOJI_URLS = OrderedDict(
    [
        ("emoji-test", "https://www.unicode.org/Public/emoji/latest/emoji-test.txt"),
        ("emoji-sequences", "https://www.unicode.org/Public/emoji/latest/emoji-sequences.txt"),
        ("emoji-zwj-sequences", "https://www.unicode.org/Public/emoji/latest/emoji-zwj-sequences.txt"),
        (
            "emoji-variation-sequences",
            "https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-variation-sequences.txt",
        ),
    ]
)


def read_url(url):
    with urlopen(url) as response:
        return response.read().decode("utf-8")


def metadata_value(text, key):
    pattern = re.compile(r"^#\s*" + re.escape(key) + r":\s*(.+)$", re.MULTILINE)
    match = pattern.search(text)
    return match.group(1).strip() if match else ""


def parse_emoji_test(text):
    rows = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or ";" not in stripped:
            continue

        codepoint_text, rest = stripped.split(";", 1)
        status_text, comment = rest.split("#", 1)
        codepoints = [int(codepoint, 16) for codepoint in codepoint_text.split()]
        status = status_text.strip().split()[0]

        # The comment is "<emoji> E<version> <name>". Keep the readable name only.
        comment_parts = comment.strip().split(maxsplit=2)
        name = comment_parts[2] if len(comment_parts) >= 3 else comment.strip()
        rows.append((codepoints, status, name))
    return rows


def contains(codepoints, codepoint):
    return codepoint in codepoints


def contains_range(codepoints, begin, end):
    return any(begin <= codepoint <= end for codepoint in codepoints)


def is_regional_indicator(codepoint):
    return 0x1F1E6 <= codepoint <= 0x1F1FF


def classify_signature(codepoints, status):
    if status == "component":
        return "component"
    if contains(codepoints, 0x20E3):
        return "keycap"
    if len(codepoints) == 2 and all(is_regional_indicator(codepoint) for codepoint in codepoints):
        return "regional_indicator_flag"
    if contains_range(codepoints, 0xE0020, 0xE007F):
        return "tag_sequence"
    if contains(codepoints, 0x200D):
        parts = []
        if contains_range(codepoints, 0x1F3FB, 0x1F3FF):
            parts.append("modifier")
        if contains(codepoints, 0x2640) or contains(codepoints, 0x2642):
            parts.append("gender")
        if contains_range(codepoints, 0x1F9B0, 0x1F9B3):
            parts.append("hair")
        if contains(codepoints, 0x2764):
            parts.append("heart")
        if contains(codepoints, 0xFE0F):
            parts.append("vs16")
        if contains(codepoints, 0xFE0E):
            parts.append("vs15")
        return "zwj:" + ("+".join(parts) if parts else "plain")
    if contains_range(codepoints, 0x1F3FB, 0x1F3FF):
        return "modifier_sequence"
    if contains(codepoints, 0xFE0F):
        return "variation_vs16"
    if contains(codepoints, 0xFE0E):
        return "variation_vs15"
    if len(codepoints) == 1:
        return "single"
    return "other_sequence"


def write_fixture(output_path, emoji_test_text, downloaded_texts):
    rows = parse_emoji_test(emoji_test_text)
    version = metadata_value(emoji_test_text, "Version")
    date = metadata_value(emoji_test_text, "Date")

    status_counts = Counter(status for _, status, _ in rows)
    signature_counts = Counter(classify_signature(codepoints, status) for codepoints, status, _ in rows)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="") as output:
        output.write("# DALI Unicode emoji fixture\n")
        output.write("# Generated by automated-tests/scripts/update-unicode-emoji-fixtures.py\n")
        output.write(f"# unicode_emoji_version: {version}\n")
        output.write(f"# emoji_test_date: {date}\n")
        output.write(f"# row_count: {len(rows)}\n")
        for key, value in UNICODE_EMOJI_URLS.items():
            digest = hashlib.sha256(downloaded_texts[key].encode("utf-8")).hexdigest()
            output.write(f"# source_{key}: {value}\n")
            output.write(f"# sha256_{key}: {digest}\n")
        output.write(
            "# status_counts: "
            + ", ".join(f"{key}={status_counts[key]}" for key in sorted(status_counts))
            + "\n"
        )
        output.write(
            "# signature_counts: "
            + ", ".join(f"{key}={signature_counts[key]}" for key in sorted(signature_counts))
            + "\n"
        )
        output.write("# fields: codepoints_hex<TAB>status<TAB>signature<TAB>name\n")

        for codepoints, status, name in rows:
            codepoint_text = " ".join(f"{codepoint:04X}" for codepoint in codepoints)
            signature = classify_signature(codepoints, status)
            output.write(f"{codepoint_text}\t{status}\t{signature}\t{name}\n")

    return rows, status_counts, signature_counts


def main():
    parser = argparse.ArgumentParser(description="Update Unicode emoji fixtures for DALI text tests.")
    parser.add_argument(
        "--output",
        default="res/emoji-test-latest.tsv",
        help="Output TSV fixture path.",
    )
    args = parser.parse_args()

    downloaded_texts = OrderedDict((key, read_url(url)) for key, url in UNICODE_EMOJI_URLS.items())
    rows, status_counts, signature_counts = write_fixture(
        Path(args.output), downloaded_texts["emoji-test"], downloaded_texts
    )

    print(f"Wrote {args.output}")
    print(f"Rows: {len(rows)}")
    print("Status counts:", ", ".join(f"{key}={status_counts[key]}" for key in sorted(status_counts)))
    print("Signature counts:", ", ".join(f"{key}={signature_counts[key]}" for key in sorted(signature_counts)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
