// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_UIELEMENTCONFIG_METHODS(ChildClass) \
  DALI_UI_CHAIN_UICONFIG_METHODS(ChildClass) \
  /** \
  * @brief Sets the default font point-size for text elements. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] fontSize The default font size in points \
  */ \
  ChildClass& SetDefaultFontSize(float fontSize) { UIElementConfig::SetDefaultFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets the default text color for text elements. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] color The default text color \
  */ \
  ChildClass& SetDefaultTextColor(const Vector4& color) { UIElementConfig::SetDefaultTextColor(color); return *this; }
