import re
import sys
import os

# API Description:
# C++ 헤더에서 Fluent API용 매크로를 생성하고 삽입합니다.
# 1. 자동 추출: void SetXXX(...) 형태의 모든 함수 (const 인자 포함)
# 2. 수동 추가: // @CHAIN_MANUAL(chainName, mapName, args...) 태그 지원
# 3. 주석 수집: 자동은 역방향, 수동(MANUAL)은 정방향으로 주석 블록 수집
# 4. 구조 최적화: #include 위치를 클래스 주석 블록 위로 자동 배치

def process_header(file_path):
  with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

  blocks = []
  is_in_block, current_block = False, None

  for i, line in enumerate(lines):
    # 블록 시작 체크
    start_m = re.search(r'//\s*@CHAIN_START\((\w+)(?:\s*,\s*(\w*))?\)', line)
    if start_m:
      is_in_block, current_block = True, {'class': start_m.group(1), 'parent': start_m.group(2) or "", 'methods': []}
      continue
    if '// @CHAIN_END' in line:
      if current_block: blocks.append(current_block)
      is_in_block = False
      continue

    if not is_in_block: continue

    # CASE 1: 수동 추가 태그 (// @CHAIN_MANUAL)
    if '@CHAIN_MANUAL' in line:
      m = re.search(r'@CHAIN_MANUAL\s*\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(.*)\)', line)
      if m:
        c_name, m_name, args_raw = m.group(1), m.group(2), m.group(3).strip()
        # [정방향 주석 수집] 태그 바로 다음 줄부터 주석 블록 확인
        doc_lines, k = [], i + 1
        if k < len(lines) and '/**' in lines[k]:
          while k < len(lines):
            doc_lines.append(lines[k].strip())
            if '*/' in lines[k]: break
            k += 1
        current_block['methods'].append({'name': c_name, 'map_to': m_name, 'args': args_raw, 'doc': doc_lines})

    # CASE 2: 자동 void Set 함수 추출
    elif line.strip().startswith('void Set'):
      match = re.search(r'void\s+Set(?P<name>\w+)\s*\(', line)
      if match:
        method_name, args_start_pos = match.group('name'), match.end()
        # 괄호 짝 맞추기로 인자 추출 (std::function 대응)
        paren_depth, extracted_args, remainder = 1, "", line[args_start_pos:]
        for char in remainder:
          if char == '(': paren_depth += 1
          elif char == ')': paren_depth -= 1
          if paren_depth == 0: break
          extracted_args += char

        # [역방향 주석 수집] 함수 선언 바로 위에서 주석 확인
        doc_lines, j = [], i - 1
        while j >= 0 and (lines[j].strip().startswith('/') or lines[j].strip().startswith('*')):
          doc_lines.insert(0, lines[j].strip())
          if '/**' in lines[j]: break
          j -= 1
        current_block['methods'].append({'name': method_name, 'map_to': 'Set' + method_name, 'args': extracted_args.strip(), 'doc': doc_lines})

  if not blocks: return

  # 2. .autogen.h 생성
  base_dir, base_name = os.path.dirname(file_path), os.path.splitext(os.path.basename(file_path))[0]
  autogen_path = os.path.join(base_dir, base_name + ".autogen.h")
  auto_output = ["// Generated by dali-ui preprocessor. Do not modify.", "#pragma once\n"]

  for b in blocks:
    m_macro_name = "SHADOW_" + b['class'].upper() + "_METHODS"
    macro_def, items = ["#define " + m_macro_name + "(ChildClass) \\"], []
    if b['parent']: items.append("  SHADOW_" + b['parent'].upper() + "_METHODS(ChildClass)")

    for m in b['methods']:
      arg_names = []
      if m['args']:
        # 꺽쇠 깊이 고려하여 인자 변수명만 추출
        parts, curr_p, d_angle = [], "", 0
        for c in m['args']:
          if c == '<': d_angle += 1
          elif c == '>': d_angle -= 1
          if c == ',' and d_angle == 0: parts.append(curr_p.strip()); curr_p = ""
          else: curr_p += c
        parts.append(curr_p.strip())
        for p in parts:
          clean_p = p.split('=')[0].strip()
          n_match = re.search(r'([\w]+)$', clean_p)
          if n_match: arg_names.append(n_match.group(1))

      m_body = ["  " + d for d in m['doc']]
      m_body += ["  ChildClass& " + m['name'] + "(" + m['args'] + ")", "  {", "    " + m['map_to'] + "(" + ", ".join(arg_names) + ");", "    return *this;", "  }"]
      items.append("\n".join(m_body))

    for i, item in enumerate(items):
      sub_lns = item.split('\n')
      for j, ln in enumerate(sub_lns):
        is_last = (i == len(items)-1 and j == len(sub_lns)-1)
        macro_def.append(ln + ("" if is_last else " \\"))
    auto_output += macro_def + [""]

  with open(autogen_path, 'w', encoding='utf-8') as f: f.write("\n".join(auto_output))

  # 3. 원본 헤더 정화 및 재삽입
  content = "".join(lines)
  content = re.sub('#include "' + base_name + '.autogen.h"\\n?', '', content)
  for b in blocks:
    m_call = "SHADOW_" + b['class'].upper() + "_METHODS(" + b['class'] + ")"
    content = re.sub(r'\n\s*public:\n\s*' + re.escape(m_call), '', content)

    class_def = re.search(r"class\s+.*?\b" + b['class'] + r"\b", content)
    if class_def:
      ins_pos = class_def.start()
      # 클래스 주석 블록 위로 include 위치 조정
      search_area = content[:ins_pos]
      doc_start = search_area.rstrip().rfind('/**')
      if doc_start != -1 and '*/' in search_area[doc_start:]: ins_pos = doc_start
      content = content[:ins_pos] + '#include "' + base_name + '.autogen.h"\n' + content[ins_pos:]

    c_end = re.search(r"class\s+.*?\b" + b['class'] + r"\b.*?(\n\s*\}?;)", content, re.DOTALL)
    if c_end:
      idx = c_end.start(1)
      content = content[:idx] + "\n\npublic:\n  " + m_call + content[idx:]

  with open(file_path, 'w', encoding='utf-8') as f: f.write(content.strip() + "\n")

if __name__ == "__main__":
  if len(sys.argv) > 1: process_header(sys.argv[1])
