import re
import sys
import os

# API Description:
# C++ Fluent API 매크로 생성기 (SetXXX 이름 보존 버전)
# 1. 자동 추출 및 Manual 태그 모두 원본 함수명(SetXXX)을 그대로 체이닝 이름으로 사용
# 2. View& SetXXX 형태의 Setter 수집 및 상속용 매크로 생성

def process_header(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    blocks = []
    is_in_block, current_block = False, None

    i = 0
    while i < len(lines):
        line = lines[i]

        # 블록 시작/끝 체크
        start_m = re.search(r'//\s*@CHAIN_START\((\w+)(?:\s*,\s*(\w*))?\)', line)
        if start_m:
            is_in_block, current_block = True, {'class': start_m.group(1), 'parent': start_m.group(2) or "", 'methods': []}
            i += 1
            continue
        if '// @CHAIN_END' in line:
            if current_block: blocks.append(current_block)
            is_in_block = False
            i += 1
            continue

        if not is_in_block:
            i += 1
            continue

        target_method = None

        # 1. MANUAL 태그 우선 확인
        if '@CHAIN_MANUAL' in line:
            k = i + 1
            while k < len(lines) and k < i + 10:
                m = re.search(r'(?P<ret>[\w&:*<>]+)\s+(?P<name>\w+)\s*\(', lines[k])
                if m and not lines[k].strip().startswith(('/', '*')):
                    target_method = {
                        'name': m.group('name'), # 이름 그대로 사용
                        'args_start': m.end(),
                        'line_idx': k
                    }
                    break
                k += 1

        # 2. 자동 Setter 추출 (Class& SetXXX)
        elif f"{current_block['class']}&" in line and "Set" in line:
            m = re.search(r'(?P<ret>[\w&:*<>]+)\s+(?P<name>Set\w+)\s*\(', line)
            if m:
                target_method = {
                    'name': m.group('name'), # 이름 그대로(Set 포함) 사용
                    'args_start': m.end(),
                    'line_idx': i
                }

        if target_method:
            idx = target_method['line_idx']
            # 괄호 짝 맞추기
            depth, args_str, rmd = 1, "", lines[idx][target_method['args_start']:]
            for char in rmd:
                if char == '(': depth += 1
                elif char == ')': depth -= 1
                if depth == 0: break
                args_str += char

            # 주석 수집
            collected_docs = []
            cursor = idx - 1
            while cursor >= 0:
                c_line = lines[cursor].strip()
                if c_line.startswith(('/', '*')):
                    if '@CHAIN_MANUAL' not in c_line:
                        collected_docs.insert(0, c_line)
                    if '/**' in c_line: break
                    cursor -= 1
                else:
                    break

            current_block['methods'].append({
                'name': target_method['name'],
                'args': args_str.strip(),
                'doc': collected_docs
            })
            if idx > i: i = idx

        i += 1

    if not blocks: return
    generate_files(file_path, blocks)

def generate_files(file_path, blocks):
    base_dir, base_name = os.path.dirname(file_path), os.path.splitext(os.path.basename(file_path))[0]
    autogen_path = os.path.join(base_dir, base_name + ".autogen.h")
    output = ["// Generated by dali-ui preprocessor. Do not modify.", "#pragma once\n"]

    for b in blocks:
        cls_upper = b['class'].upper()
        chain_macro = f"DALI_UI_CHAIN_{cls_upper}_METHODS"
        c_lines = [f"#define {chain_macro}(ChildClass) \\"]
        c_items = []
        if b['parent']:
            c_items.append(f"  DALI_UI_CHAIN_{b['parent'].upper()}_METHODS(ChildClass)")
        for m in b['methods']:
            names = extract_arg_names(m['args'])
            body = ["  " + d for d in m['doc']]
            # 이름 그대로 호출 및 반환
            body += [f"  ChildClass& {m['name']}({m['args']}) {{ {b['class']}::{m['name']}({', '.join(names)}); return *this; }}"]
            c_items.append("\n".join(body))
        output += build_macro(c_lines, c_items) + [""]

    with open(autogen_path, 'w', encoding='utf-8') as f: f.write("\n".join(output))
    update_header(file_path, blocks, base_name)

def extract_arg_names(args_raw):
    names, curr, angle = [], "", 0
    parts = []
    for c in args_raw:
        if c == '<': angle += 1
        elif c == '>': angle -= 1
        if c == ',' and angle == 0: parts.append(curr.strip()); curr = ""
        else: curr += c
    parts.append(curr.strip())
    for p in parts:
        if p:
            clean = p.split('=')[0].strip()
            m = re.search(r'([\w]+)$', clean)
            if m: names.append(m.group(1))
    return names

def build_macro(header, items):
    res = header
    for i, item in enumerate(items):
        sub = item.split('\n')
        for j, ln in enumerate(sub):
            is_last = (i == len(items)-1 and j == len(sub)-1)
            res.append(ln + ("" if is_last else " \\"))
    return res

def update_header(path, blocks, base_name):
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    content = re.sub(f'#include "{base_name}.autogen.h"\\n?', '', content)
    for b in blocks:
        content = re.sub(r'\n\s*public:\n\s*DALI_UI_CHAIN_.*_METHODS\(.*\)', '', content)
        c_def = re.search(r"class\s+.*?\b" + b['class'] + r"\b", content)
        if c_def:
            ins = c_def.start()
            search = content[:ins]
            doc = search.rstrip().rfind('/**')
            if doc != -1 and '*/' in search[doc:]: ins = doc
            content = content[:ins] + f'#include "{base_name}.autogen.h"\n' + content[ins:]
        if b['parent']:
            p_call = f"DALI_UI_CHAIN_{b['parent'].upper()}_METHODS({b['class']})"
            c_end = re.search(r"class\s+.*?\b" + b['class'] + r"\b.*?(\n\s*\}?;)", content, re.DOTALL)
            if c_end:
                idx = c_end.start(1)
                content = content[:idx] + f"\n\npublic:\n  {p_call}" + content[idx:]
    with open(path, 'w', encoding='utf-8') as f: f.write(content.strip() + "\n")

if __name__ == "__main__":
    if len(sys.argv) > 1: process_header(sys.argv[1])
