import re
import sys
import os

# API Description:
# C++ Fluent API 매크로 생성기 (중복 제거 버전)
# 1. SELF_XXX: 본인 클래스의 SetXXX 호출 메소드 자동 생성.
# 2. CHAIN_XXX: 부모 CHAIN + 본인 SELF + 본인 MANUAL 통합.

def process_header(file_path):
  with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

  blocks = []
  is_in_block, current_block = False, None

  for i, line in enumerate(lines):
    start_m = re.search(r'//\s*@CHAIN_START\((\w+)(?:\s*,\s*(\w*))?\)', line)
    if start_m:
      is_in_block, current_block = True, {
        'class': start_m.group(1),
        'parent': start_m.group(2) or "",
        'methods': [],
        'manual_methods': []
      }
      continue
    if '// @CHAIN_END' in line:
      if current_block: blocks.append(current_block)
      is_in_block = False
      continue

    if not is_in_block: continue

    # @CHAIN_MANUAL 파싱
    if '@CHAIN_MANUAL' in line:
      target_idx = i + 1
      while target_idx < len(lines) and (lines[target_idx].strip().startswith('/') or lines[target_idx].strip().startswith('*')):
        target_idx += 1
      if target_idx < len(lines):
        func_match = re.search(r'\w+[&*]?\s+(?P<name>\w+)\s*\(', lines[target_idx])
        if func_match:
          m_name, args_start = func_match.group('name'), func_match.end()
          depth, args_str, rmd = 1, "", lines[target_idx][args_start:]
          for char in rmd:
            if char == '(': depth += 1
            elif char == ')': depth -= 1
            if depth == 0: break
            args_str += char
          doc_lines, k = [], i + 1
          while k < target_idx:
            if lines[k].strip(): doc_lines.append(lines[k].strip())
            k += 1
          current_block['manual_methods'].append({'name': m_name, 'args': args_str.strip(), 'doc': doc_lines})

    # void Set 추출
    elif line.strip().startswith('void Set'):
      match = re.search(r'void\s+Set(?P<name>\w+)\s*\(', line)
      if match:
        m_name, args_start = match.group('name'), match.end()
        depth, args_str, rmd = 1, "", line[args_start:]
        for char in rmd:
          if char == '(': depth += 1
          elif char == ')': depth -= 1
          if depth == 0: break
          args_str += char
        doc_lines, j = [], i - 1
        while j >= 0 and (lines[j].strip().startswith('/') or lines[j].strip().startswith('*')):
          doc_lines.insert(0, lines[j].strip())
          if '/**' in lines[j]: break
          j -= 1
        current_block['methods'].append({'name': m_name, 'args': args_str.strip(), 'doc': doc_lines})

  if not blocks: return

  base_dir, base_name = os.path.dirname(file_path), os.path.splitext(os.path.basename(file_path))[0]
  autogen_path = os.path.join(base_dir, base_name + ".autogen.h")
  output = ["// Generated by dali-ui preprocessor. Do not modify.", "#pragma once\n"]

  for b in blocks:
    cls_upper = b['class'].upper()
    self_macro = f"DALI_UI_SELF_{cls_upper}_METHODS"
    chain_macro = f"DALI_UI_CHAIN_{cls_upper}_METHODS"

    # --- 1. SELF 매크로 (자동 추출 메소드 정의) ---
    s_lines = [f"#define {self_macro}(ChildClass) \\"]
    s_items = []
    for m in b['methods']:
      names = extract_arg_names(m['args'])
      body = ["  " + d for d in m['doc']]
      body += [f"  ChildClass& {m['name']}({m['args']}) {{ Set{m['name']}({', '.join(names)}); return *this; }}"]
      s_items.append("\n".join(body))
    output += build_macro(s_lines, s_items) + [""]

    # --- 2. CHAIN 매크로 (중복 제거된 통합 버전) ---
    c_lines = [f"#define {chain_macro}(ChildClass) \\"]
    c_items = []

    # A. 부모의 CHAIN 호출
    if b['parent']:
      c_items.append(f"  DALI_UI_CHAIN_{b['parent'].upper()}_METHODS(ChildClass)")

    # B. 본인의 SELF 호출 (지유님 제안 반영)
    c_items.append(f"  {self_macro}(ChildClass)")

    # C. 수동 MANUAL 메소드만 별도로 정의
    for m in b['manual_methods']:
      names = extract_arg_names(m['args'])
      body = ["  " + d for d in m['doc']]
      # 상속용이므로 클래스 명시 호출 유지
      body += [f"  ChildClass& {m['name']}({m['args']}) {{ {b['class']}::{m['name']}({', '.join(names)}); return *this; }}"]
      c_items.append("\n".join(body))

    output += build_macro(c_lines, c_items) + [""]

  with open(autogen_path, 'w', encoding='utf-8') as f: f.write("\n".join(output))
  update_header(file_path, lines, blocks, base_name)

# Helper functions (extract_arg_names, build_macro, update_header) 동일함
def extract_arg_names(args_raw):
  names, curr, angle = [], "", 0
  parts = []
  for c in args_raw:
    if c == '<': angle += 1
    elif c == '>': angle -= 1
    if c == ',' and angle == 0: parts.append(curr.strip()); curr = ""
    else: curr += c
  parts.append(curr.strip())
  for p in parts:
    if p:
      clean = p.split('=')[0].strip()
      m = re.search(r'([\w]+)$', clean)
      if m: names.append(m.group(1))
  return names

def build_macro(header, items):
  res = header
  for i, item in enumerate(items):
    sub = item.split('\n')
    for j, ln in enumerate(sub):
      is_last = (i == len(items)-1 and j == len(sub)-1)
      res.append(ln + ("" if is_last else " \\"))
  return res

def update_header(path, lines, blocks, base_name):
  content = "".join(lines)
  content = re.sub(f'#include "{base_name}.autogen.h"\\n?', '', content)
  for b in blocks:
    m_call = f"DALI_UI_SELF_{b['class'].upper()}_METHODS({b['class']})"
    content = re.sub(r'\n\s*public:\n\s*' + re.escape(m_call), '', content)
    c_def = re.search(r"class\s+.*?\b" + b['class'] + r"\b", content)
    if c_def:
      ins = c_def.start()
      search = content[:ins]
      doc = search.rstrip().rfind('/**')
      if doc != -1 and '*/' in search[doc:]: ins = doc
      content = content[:ins] + f'#include "{base_name}.autogen.h"\n' + content[ins:]
    c_end = re.search(r"class\s+.*?\b" + b['class'] + r"\b.*?(\n\s*\}?;)", content, re.DOTALL)
    if c_end:
      idx = c_end.start(1)
      content = content[:idx] + f"\n\npublic:\n  {m_call}" + content[idx:]
  with open(path, 'w', encoding='utf-8') as f: f.write(content.strip() + "\n")

if __name__ == "__main__":
  if len(sys.argv) > 1: process_header(sys.argv[1])
