// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_FLEXLAYOUT_METHODS(ChildClass) \
  DALI_UI_CHAIN_LAYOUT_METHODS(ChildClass) \
  /** \
  * @brief Sets the flex direction. \
  * \
  * @param[in] direction The flex direction \
  */ \
  ChildClass& SetDirection(FlexDirection direction) { FlexLayout::SetDirection(direction); return *this; } \
  /** \
  * @brief Sets the wrap behavior. \
  * \
  * @param[in] wrap The wrap behavior \
  */ \
  ChildClass& SetWrap(FlexWrap wrap) { FlexLayout::SetWrap(wrap); return *this; } \
  /** \
  * @brief Sets the justify content alignment. \
  * \
  * @param[in] justify The justify content value \
  */ \
  ChildClass& SetJustifyContent(FlexJustify justify) { FlexLayout::SetJustifyContent(justify); return *this; } \
  /** \
  * @brief Sets the align items value. \
  * \
  * @param[in] align The align items value \
  */ \
  ChildClass& SetAlignItems(FlexAlign align) { FlexLayout::SetAlignItems(align); return *this; } \
  /** \
  * @brief Sets the align content value (for wrapped lines). \
  * \
  * @param[in] align The align content value \
  */ \
  ChildClass& SetAlignContent(FlexAlign align) { FlexLayout::SetAlignContent(align); return *this; }
