// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_FLEX_LAYOUT_METHODS(ChildClass) \
  DALI_UI_CHAIN_LAYOUT_METHODS(ChildClass) \
  ChildClass& SetDirection(FlexDirection direction) { FlexLayout::SetDirection(direction); return *this; } \
  ChildClass& SetWrap(FlexWrap wrap) { FlexLayout::SetWrap(wrap); return *this; } \
  ChildClass& SetJustifyContent(FlexJustify justify) { FlexLayout::SetJustifyContent(justify); return *this; } \
  ChildClass& SetAlignItems(FlexAlign align) { FlexLayout::SetAlignItems(align); return *this; } \
  ChildClass& SetAlignContent(FlexAlign align) { FlexLayout::SetAlignContent(align); return *this; }
