// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_GRIDLAYOUT_METHODS(ChildClass) \
  DALI_UI_CHAIN_LAYOUT_METHODS(ChildClass) \
  /** \
  * @brief Sets all row definitions at once. \
  * \
  * @param[in] rows Vector of row height specifications \
  */ \
  ChildClass& SetRowDefinitions(const Dali::Vector<GridLength>& rows) { GridLayout::SetRowDefinitions(rows); return *this; } \
  /** \
  * @brief Sets all column definitions at once. \
  * \
  * @param[in] columns Vector of column width specifications \
  */ \
  ChildClass& SetColumnDefinitions(const Dali::Vector<GridLength>& columns) { GridLayout::SetColumnDefinitions(columns); return *this; } \
  /** \
  * @brief Sets the row spacing. \
  * \
  * @param[in] spacing The spacing between rows \
  */ \
  ChildClass& SetRowSpacing(float spacing) { GridLayout::SetRowSpacing(spacing); return *this; } \
  /** \
  * @brief Sets the column spacing. \
  * \
  * @param[in] spacing The spacing between columns \
  */ \
  ChildClass& SetColumnSpacing(float spacing) { GridLayout::SetColumnSpacing(spacing); return *this; }
