// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_GRID_LAYOUT_METHODS(ChildClass) \
  DALI_UI_CHAIN_LAYOUT_METHODS(ChildClass) \
  ChildClass& SetRowDefinitions(const Dali::Vector<GridLength>& rows) { GridLayout::SetRowDefinitions(rows); return *this; } \
  ChildClass& SetColumnDefinitions(const Dali::Vector<GridLength>& columns) { GridLayout::SetColumnDefinitions(columns); return *this; } \
  ChildClass& SetRowSpacing(float spacing) { GridLayout::SetRowSpacing(spacing); return *this; } \
  ChildClass& SetColumnSpacing(float spacing) { GridLayout::SetColumnSpacing(spacing); return *this; }
