// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_STACK_LAYOUT_METHODS(ChildClass) \
  DALI_UI_CHAIN_LAYOUT_METHODS(ChildClass) \
  ChildClass& SetOrientation(StackOrientation orientation) { StackLayout::SetOrientation(orientation); return *this; } \
  ChildClass& SetSpacing(float spacing) { StackLayout::SetSpacing(spacing); return *this; }
