// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_STACKLAYOUT_METHODS(ChildClass) \
  DALI_UI_CHAIN_LAYOUT_METHODS(ChildClass) \
  /** \
  * @brief Sets the orientation of the stack layout. \
  * \
  * @param[in] orientation The orientation to set \
  */ \
  ChildClass& SetOrientation(StackOrientation orientation) { StackLayout::SetOrientation(orientation); return *this; } \
  /** \
  * @brief Sets the spacing between children in the stack. \
  * \
  * @param[in] spacing The spacing to set (in pixels) \
  */ \
  ChildClass& SetSpacing(float spacing) { StackLayout::SetSpacing(spacing); return *this; }
